-- DatNest Core Platform - Complete Land Use Codes Population
-- Migration: 002b_populate_land_use_codes.sql
-- Populates ALL 349 standardized land use codes with intelligent categorization

-- Set schema
SET search_path TO datnest, public;

-- Clear existing data (in case of re-run)
TRUNCATE TABLE land_use_codes;

-- =====================================================
-- POPULATE ALL LAND USE CODES WITH INTELLIGENCE
-- =====================================================

INSERT INTO land_use_codes (code, description, category, is_residential, is_commercial, is_industrial, is_agricultural, is_vacant, is_exempt) VALUES
-- Miscellaneous (0000-0999)
('0010', 'Miscellaneous (General)', 'Miscellaneous', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0011', 'Pipeline or Right-of-Way', 'Miscellaneous', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0012', 'Rail (Right-of-way & track)', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0013', 'Road (Right-of-way)', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0014', 'Utilities (Right-of-way ONLY)', 'Utilities', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0015', 'Sub-Surface Rights (mineral)', 'Rights', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0016', 'Surface Rights (Grazing, timber, coal, etc.)', 'Rights', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0017', 'Leasehold Rights (misc.)', 'Rights', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0018', 'Possessory Interest (misc.)', 'Rights', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0019', 'Petroleum & Gas Wells (misc.)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('0020', 'Water Rights (misc.)', 'Rights', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0021', 'Right-of-Way (not rail, road or utility)', 'Rights', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0022', 'Easement (misc.)', 'Rights', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0023', 'Homestead (Misc.)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0024', 'Common Area (misc.)', 'Common Area', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0025', 'Royalty Interest', 'Rights', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0026', 'Working Interest', 'Rights', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0027', 'Parcels with improvements, Use Not Specified', 'Unspecified', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- Personal Property (0500-0599)
('0500', 'Personal property (general)', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0510', 'Vehicles (general)', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0511', 'Motor vehicles (cars, trucks, etc.)', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0512', 'Recreational Vehicles / Travel Trailers', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0513', 'Watercraft (ships, boats, PWCs, etc.)', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0514', 'Aircraft', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0515', 'Rolling stock (railroad)', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0516', 'Spacecraft', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0519', 'Misc vehicles not otherwise classed (antiques, etc.)', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0520', 'Business personal property (general)', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0521', 'Equipment / supplies', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0522', 'Inventory', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0523', 'Goods in transit', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0524', 'Livestock (animals, fish, birds, etc.)', 'Personal Property', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('0525', 'Crops (in ground)', 'Personal Property', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('0526', 'Crops (harvested)', 'Personal Property', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('0529', 'Misc. Business Personal Property not otherwise classed', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0530', 'Structures (general)', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0532', 'Structures on Leased Land', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0533', 'Temporary structures', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0539', 'Misc structures not otherwise classed (billboards, etc.)', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0540', 'Intangible personal property', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('0599', 'Misc personal property not otherwise classed', 'Personal Property', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- Single Family Residential (1000-1099)
('1000', 'Residential (General) (Single)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1001', 'Single Family Residential', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1002', 'Townhouse (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1003', 'Cluster home (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1004', 'Condominium Unit (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1005', 'Cooperative Unit (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1006', 'Mobile/Manufactured Home (regardless of Land ownership)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1007', 'Row House (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1008', 'Rural/Agricultural Residence', 'Residential', TRUE, FALSE, FALSE, TRUE, FALSE, FALSE),
('1009', 'Planned Unit Development (PUD) (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1010', 'Residential Common Area (Condo/PUD/etc.)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1011', 'Timeshare (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1012', 'Seasonal, Cabin, Vacation Residence', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1013', 'Bungalow (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1014', 'Zero Lot Line (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1015', 'Misc Residential Improvement', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1016', 'Modular/Pre-Fabricated Homes', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1017', 'Patio Home', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1018', 'Garden Home', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1019', 'Landominium', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1020', 'Barndominium', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1021', 'Tiny House', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1022', 'Single Family Residential w/ADU', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1023', 'Accessory Dwelling Unit (ADU)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1024', 'Single Family Residential - Two or more SFR on one parcel', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1025', 'Horizontal Property Regime', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- Multi-Family Residential (1100-1199)
('1100', 'Residential Income (General) (Multi-Family)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1101', 'Duplex (2 units, any combination)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1102', 'Triplex (3 units, any combination)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1103', 'Quadruplex (4 units, any combination)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1104', 'Apartment House (5+ units)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1105', 'Apartment House (100+ units)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1106', 'Garden Apt, Court Apt (5+ units)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1107', 'Highrise Apartments', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1108', 'Boarding House, Rooming House, Apt Hotel, Transient Lodgings, Hostel', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1109', 'Mobile Home Park, Trailer Park', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1110', 'Multi-Family Dwellings (Generic, any combination 2+)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1111', 'Fraternity House, Sorority House', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1112', 'Apartments (generic)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1113', 'Dormitory, Group Quarters (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1114', 'Residential Condominium Development (Association Assessment)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1124', 'Condominium Building (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1125', 'Cooperative Building (Residential)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1126', 'Apartment House (fewer than 5 units)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- Residential Support (1900s)
('1901', 'Residential Parking Garage', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1902', 'Residential Storage Space', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('1999', 'Single Family Residential (Assumed)', 'Residential', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- Commercial (2000-2999)
('2000', 'Commercial (General)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2001', 'Retail Stores ( Personal Services, Photography, Travel)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2002', 'Store (multi-story)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2003', 'Store/Office (mixed use)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2004', 'Department Store (apparel, household goods, furniture)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2005', 'Department Store (multi-story)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2006', 'Grocery, Supermarket', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2007', 'Regional: Shopping Center, Mall (w/Anchor)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2008', 'Community: Shopping Plaza, Shopping Center, Mini-Mall', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2009', 'Neighborhood: Shopping Center, Strip Center, Enterprise Zone', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2010', 'Shopping Center COMMON AREA (parking, etc.)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2011', 'Veterinary, Animal Hospital', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2012', 'Restaurant', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2013', 'Fast Food Restaurant / Drive-thru', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2014', 'Take-out Restaurant (food preparation)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2015', 'Bakery', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2016', 'Bar, Tavern', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2017', 'Liquor Store', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2018', 'Convenience store (7-11)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2019', 'Convenience Store (w/fuel pump)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2020', 'Service station (full service)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2021', 'Service station w/convenience store (food mart)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2022', 'Truck stop (fuel and diner)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2023', 'Vehicle Rentals, Vehicle Sales (auto/truck/RV/boat/etc.)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2024', 'Auto repair (& related), Garage', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2025', 'Car wash', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2026', 'Dry Cleaner, Laundry Service', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2027', 'Service Shop (TV, radio, electric, plumbing)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2028', 'Florist, Nursery, Greenhouse (retail/wholesale)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2029', 'Wholesale Outlet, Discount Store', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2030', 'Printer/Delivery - Retail (Kinkos, UPS, FedEx, etc.)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2031', 'Mini-Warehouse, Self-Storage', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2032', 'Day care, Pre-school (Commercial)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2033', 'Motel', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2034', 'Hotel', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2035', 'Parking Garage, Parking Structure', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2036', 'Parking Lot', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2037', 'Funeral Home, Mortuary (Commercial)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2038', 'Casino', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2039', 'Hotel-Resort', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2040', 'Hotel/Motel', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2041', 'Gas Station', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2042', 'Retail/Residential (mixed use)', 'Commercial', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2043', 'Commercial Building, Mail Order, Show Room (non-auto), Commercial Whse', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2044', 'Commercial/Office/Residential (mixed use)', 'Commercial', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2045', 'Appliance Store (Best Buy, HH Gregg)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2046', 'Kennel', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2047', 'Laundromat (self-service)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2048', 'Nightclub (Cocktail Lounge)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2050', 'Farm Supply & Equipment (retail)', 'Commercial', FALSE, TRUE, FALSE, TRUE, FALSE, FALSE),
('2051', 'Home Improvement, Garden Center (Home Depot, Lowe''s)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2052', 'Commercial Condominium (not offices)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2053', 'Drug Store / Pharmacy (CVS, Walgreens)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2054', 'Bed & Breakfast', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2055', 'Barber/Hair Salon', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2056', 'Pet Boarding & Grooming', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2057', 'Roadside Market', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2058', 'Car Wash - Automated', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2059', 'Car Wash - Self-Serve', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('2060', 'Cannabis Dispensary', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),

-- Commercial Office (3000-3999)
('3000', 'Commercial Office (General)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3001', 'Professional Bldg (legal; insurance; real estate; business)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3002', 'Professional Bldg (multi-story)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3003', 'Office Bldg (General)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3004', 'Office Bldg (multi-story)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3005', 'Dental Bldg', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3006', 'Medical Bldg/Clinic', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3007', 'Financial Bldg (Bank, S&L; Mtge; Loan; Credit)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3008', 'Condominium Offices', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3009', 'Skyscraper/Highrise (Commercial Offices)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3010', 'Commercial/Industrial (mixed use)', 'Commercial', FALSE, TRUE, TRUE, FALSE, FALSE, FALSE),
('3011', 'Common Area (commercial, not shopping center or Association Asmnt.)', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('3012', 'Mobile Commercial Units', 'Commercial', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),

-- Recreational/Entertainment (4000-4999)
('4000', 'Recreational/Entertainment (General)', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4001', 'Recreation Center', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4002', 'Public Swimming Pool', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4003', 'Boat Slips, Marina, Yacht Club (recreation/pleasure), Boat Landing', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4004', 'Bowling Alley', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4005', 'Arcades (Amusement)', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4006', 'Skating rink, Ice Skating, Roller Skating', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4007', 'Clubs, Lodges, Professional Associations', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4008', 'Museums, Library, Art Gallery (Recreational)', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4009', 'Country Club', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4010', 'Stadiums', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4011', 'Arenas, Convention Center', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4012', 'Auditoriums', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4013', 'Driving Range (Golf)', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4014', 'Race track (auto; dog; horse)', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4015', 'Gym, Health Spa', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4016', 'Dance Hall', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4017', 'Riding Stable, Trails', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4018', 'Campground, RV Park', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4019', 'Fairgrounds', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4020', 'Theater', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4021', 'Drive-In Theater', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4022', 'Amusement Park, Tourist Attraction', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4023', 'Piers, Wharf (Recreation)', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4024', 'Fish Camps, Game Club, Target Shooting', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4025', 'Outdoor Recreation: Beach, Mountain, Desert', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4026', 'Pool Hall, Billiard Parlor', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4027', 'Park, Playground, Picnic Area', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4028', 'Golf Course', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4029', 'Racquet Court, Tennis Court', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4030', 'Zoo', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4031', 'Go-carts, Miniature Golf, Water slides', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('4032', 'Sports Complex', 'Recreational', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),

-- Light Industrial (5000-5999)
('5000', 'Industrial (General)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5001', 'Manufacturing (light)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5002', 'Light Industrial (10% improved office space; Machine Shop)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5003', 'Warehouse (Industrial)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5004', 'Storage yard, Open Storage (light equipment, material)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5005', 'Food Packing, Packing Plant (fruit; vegetable; meat, dairy)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5006', 'Assembly (light industrial)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5007', 'Food Processing (candy; bakery; potato chips)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5008', 'Recycling (metal; paper; glass; etc.)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5009', 'Communications (see 6500 series)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5010', 'Condominiums (Industrial)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5011', 'R&D Facility, Laboratory, Research Facility, Cosmetics, Pharmaceutical', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5012', 'Industrial Park', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5013', 'Multi-Tenant Industrial Bldg.', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5014', 'Marine Facility/Boat Repairs (small craft or sailboat)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5015', 'Lumber & Wood Product Manufacturing (including furniture)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5016', 'Paper Product Manufacturing & related products', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5017', 'Printing & Publishing (Light Industrial)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5018', 'Industrial Loft Building, Loft Building', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5019', 'Construction/Contracting Services (Industrial)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('5020', 'Common Area (Industrial)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),

-- Heavy Industrial (6000-6499)
('6000', 'Heavy Industrial (General)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6001', 'Transportation', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6002', 'Distribution Warehouse (Regional)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6003', 'Mining facility (oil; gas; mineral, precious metals)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6004', 'Storage yard (junk; auto wrecking, salvage)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6005', 'Distillery, Brewery, Bottling', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6006', 'Refinery, Petroleum Products', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6007', 'Mill (feed; grain; paper; lumber; textile; pulp)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6008', 'Factory (apparel, textile products, leather, medium mfg.)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6009', 'Processing Plant (minerals; cement; rock; gravel; glass; clay)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6010', 'Lumberyard, Building Materials', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6011', 'Shipyard/Storage - Built or Repaired (seagoing vessels)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6012', 'Slaughter House, Stockyard', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6013', 'Waste Disposal, Sewage (processing; disposal; storage; treatment)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6014', 'Quarries (sand; gravel; rock)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6015', 'Heavy Manufacturing', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6016', 'Labor Camps (Industrial)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6017', 'Winery', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6018', 'Chemical', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6019', 'Foundry, Industrial Plant (metal; rubber; plastic)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6020', 'Cannery', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6021', 'Bulk Storage, Tanks (gasoline, fuel, etc.)', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6022', 'Grain Elevator', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6023', 'Dump Site', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6024', 'Cold Storage', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('6025', 'Sugar Refinery', 'Industrial', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),

-- Transportation & Communications (6500-6999)
('6500', 'Transportation & Communications (General)', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6501', 'Airport & related', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6502', 'Railroad & related', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6503', 'Freeways, State Hwys', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6504', 'Roads, Streets, Bridges', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6505', 'Bus Terminal', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6506', 'Telegraph, Telephone', 'Utilities', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6507', 'Radio or TV Station', 'Utilities', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6508', 'Truck Terminal (Motor Freight)', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6509', 'Cable TV Station', 'Utilities', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6510', 'Harbor & Marine Transportation', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6511', 'Microwave', 'Utilities', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6512', 'Commercial Auto Transportation/Storage', 'Transportation', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6513', 'Pollution Control', 'Utilities', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('6514', 'Cellular', 'Utilities', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- Agricultural (7000-7999)
('7000', 'Agricultural / Rural (General)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7001', 'Farm (Irrigated or Dry)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7002', 'Ranch', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7003', 'Range land (grazing)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7004', 'Crop land, Field Crops, Row Crops (all soil classes)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7005', 'Orchard (fruit; nut)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7006', 'Vineyard (Agricultural)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7007', 'Poultry Farm (chicken; turkey; fish; bees; rabbits)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7008', 'Dairy Farm', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7009', 'Timberland, Forest, Trees (Agricultural)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7010', 'Wildlife (Refuge)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7011', 'Desert or Barren Land', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7012', 'Pasture, Meadow', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7013', 'Misc. Structures - Ranch, Farm, Fixtures', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7014', 'Grove (Agricultural)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7015', 'Feedlots', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7016', 'Livestock parcel', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7017', 'Horticulture, Growing Houses, Ornamental (Agricultural)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7018', 'Well Site (Agricultural)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7019', 'Truck Crops (tobacco; cash crops)', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7020', 'Reservoir, Water Supply', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7021', 'Irrigation, Flood Control', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7022', 'Natural Resources', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7023', 'Rural Improved / Non-Residential', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),
('7024', 'Cannabis Grow Facility', 'Agricultural', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE),

-- Vacant Land (8000-8999)
('8000', 'Vacant Land (General)', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8001', 'Residential-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8002', 'Commercial-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8003', 'Industrial-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8004', 'Private Preserve, Open Space-Vacant Land (Forest Land, Conservation)', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8005', 'Institutional-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8006', 'Government-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8007', 'Multi-Family-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8008', 'Rural/Agricultural-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, TRUE, TRUE, FALSE),
('8009', 'Waste Land, Marsh, Swamp, Submerged-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8010', 'Recreational-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8011', 'Water Area (Lakes; River; Shore)-Vacant Land', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8012', 'Unusable Land (Remnant, Steep, etc.)', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8013', 'Abandoned Site, Contaminated Site', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8014', 'Under Construction', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8015', 'Vacant Land - Destroyed/Uninhabitable Improvement', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8016', 'Vacant Land - Unspecified Improvement', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
('8017', 'Vacant Land - Exempt', 'Vacant', FALSE, FALSE, FALSE, FALSE, TRUE, TRUE),

-- Special Purpose (8500s)
('8500', 'Special Purpose', 'Special', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('8501', 'State Board of Equalization - Special Assessments', 'Special', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('8502', 'Regulating Districts & Assessments; Tax Abatement', 'Special', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('8503', 'Redevelopment Agency or Zone', 'Special', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('8504', 'Centrally Assessed', 'Special', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),

-- Exempt (9000-9999)
('9000', 'Exempt (full or partial)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9001', 'Native American Lands / American Indian Lands', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),

-- Institutional (9100s)
('9100', 'Institutional (General)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9101', 'Religious, Church, Worship (Synagogue, Temple, Parsonage)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9102', 'Parochial School, Private School', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9103', 'College, University, Vocational school-PRIVATE', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9104', 'Hospital-PRIVATE', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9105', 'Medical Clinic', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9106', 'Homes (retired; handicap, rest; convalescent; nursing)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9107', 'Children''s Home, Orphanage', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9108', 'Cemetery (Exempt)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9109', 'Crematorium, Mortuary (Exempt)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9110', 'Charitable organization, Fraternal', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9111', 'Recreational Non-Taxable (Camps, Boy/Girl Scouts)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9112', 'Private Utility (electric, water, gas, nuclear, solar, wind, etc.)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),

-- Government (9200s)
('9200', 'Governmental/Public Use (General)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9201', 'Military (office; base; post; port; reserve; weapon range; test sites)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9202', 'Forest (park; reserve; recreation, conservation)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9203', 'Public School (administration; campus; dorms; instruction)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9204', 'Colleges, University-PUBLIC', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9205', 'Post Office', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9206', 'Cultural, Historical (monuments; homes; museums; other)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9207', 'Govt. Administrative Office (Federal; State; Local; Court House)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9208', 'Emergency (Police; Fire; Rescue; Shelters, Animal Shelter)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9209', 'Other exempt property', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9210', 'City, Municipal, Town, Village Owned (Exempt)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9211', 'County Owned (Exempt)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9212', 'State Owned (Exempt)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9213', 'Federal Property (Exempt)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9214', 'Public Health Care Facility (Exempt)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9215', 'Community Center (Exempt)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9216', 'Public Utility (electric, water, gas, nuclear, solar, wind, etc.)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9217', 'Welfare, Social Service, Low Income Housing (Exempt)', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9218', 'Correctional Facility, Jails, Prisons, Insane Asylum', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
('9219', 'Hospital-PUBLIC', 'Exempt', FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),

-- Historical (9300s)
('9300', 'Historical-PRIVATE (General)', 'Historical', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('9301', 'Historical Residence', 'Historical', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
('9302', 'Historical Retail', 'Historical', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('9303', 'Historical Warehouse', 'Historical', FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
('9304', 'Historical Office', 'Historical', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('9305', 'Historical Transient Lodging (hotel/motel)', 'Historical', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('9307', 'Historical Recreation, Entertainment', 'Historical', FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
('9308', 'Historical Park / Site', 'Historical', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
('9309', 'Historical District', 'Historical', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE);

-- =====================================================
-- CREATE INDEXES ON LOOKUP TABLE
-- =====================================================
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_land_use_codes_category 
    ON land_use_codes(category);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_land_use_codes_residential 
    ON land_use_codes(is_residential) WHERE is_residential = TRUE;

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_land_use_codes_commercial 
    ON land_use_codes(is_commercial) WHERE is_commercial = TRUE;

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_land_use_codes_industrial 
    ON land_use_codes(is_industrial) WHERE is_industrial = TRUE;

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_land_use_codes_agricultural 
    ON land_use_codes(is_agricultural) WHERE is_agricultural = TRUE;

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_land_use_codes_vacant 
    ON land_use_codes(is_vacant) WHERE is_vacant = TRUE;

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_land_use_codes_exempt 
    ON land_use_codes(is_exempt) WHERE is_exempt = TRUE;