/* OpenLien DataSet */

-- =============================================
-- Author:		Ashish Bathini
-- Create date: 07/22/2019
-- Revised: 01/15/2020
-- Version Update : V1.1
-- Description: Load scripts for OpenLien Dataset
-- =============================================

 /* Create a Staging table to import the OpenLien dataset  */

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Quantarium_Staging_OpenLienData](
	[Quantarium_Internal_PID] [varchar](500)NOT NULL,
[FIPS_Code] [varchar](500)NOT NULL,
[Assessors_Parcel_Number] [varchar](500) NULL,
[Duplicate_APN] [varchar](500) NULL,
[Tax_Account_Number] [varchar](500) NULL,
[Current_Owner_Name] [varchar](500) NULL,
[CO_Mail_Care_of_Name] [varchar](500) NULL,
[CO_Mail_Street_Address] [varchar](500) NULL,
[CO_Mailing_City] [varchar](500) NULL,
[CO_Mailing_State] [varchar](500) NULL,
[CO_Mailing_Zip_Code] [varchar](500) NULL,
[CO_Mailing_Zip_Plus4Code] [varchar](500) NULL,
[CO_Unit_Number] [varchar](500) NULL,
[CO_Unit_Type] [varchar](500) NULL,
[Mail_Care_Of_Name_Indicator] [varchar](500) NULL,
[Owner_Occupied] [varchar](500) NULL,
[Owner1FirstName] [varchar](500) NULL,
[Owner1MiddleName] [varchar](500) NULL,
[Owner1LastName] [varchar](500) NULL,
[Owner2Firstname] [varchar](500) NULL,
[Owner2MiddleName] [varchar](500) NULL,
[Owner2LastName] [varchar](500) NULL,
[ParsedOwnerSourceCode] [varchar](500) NULL,
[Buyer_ID_Code_1] [varchar](500) NULL,
[Buyer_Vesting_Code] [varchar](500) NULL,
[Length_of_Residence_Months] [varchar](500) NULL,
[Length_of_Residence_Code] [varchar](500) NULL,
[Ownership_Start_Date] [varchar](500) NULL,
[LSale_Book_Number] [varchar](500) NULL,
[LSale_Page_Number] [varchar](500) NULL,
[LSale_Document_Number] [varchar](500) NULL,
[LSale_Document_Type_Code] [varchar](500) NULL,
[LSale_Price] [varchar](500) NULL,
[LSale_Price_Code] [varchar](500) NULL,
[LSale_Recording_Date] [varchar](500) NULL,
[LSale_reo_flag] [varchar](500) NULL,
[LSale_distressed_sale_flag] [varchar](500) NULL,
[Last_Transfer_Date] [varchar](500) NULL,
[LValid_Book_Number] [varchar](500) NULL,
[LValid_Page_Number] [varchar](500) NULL,
[LValid_Document_Number] [varchar](500) NULL,
[LValid_Document_Type_Code] [varchar](500) NULL,
[LValid_Price] [varchar](500) NULL,
[LValid_Price_Code] [varchar](500) NULL,
[LValid_Recording_Date] [varchar](500) NULL,
[LValid_reo_flag] [varchar](500) NULL,
[LValid_distressed_sale_flag] [varchar](500) NULL,
[Last_Sale_date] [varchar](500) NULL,
[PSale_Book_Number] [varchar](500) NULL,
[PSale_Page_Number] [varchar](500) NULL,
[PSale_Document_Number] [varchar](500) NULL,
[PSale_Document_Type_Code] [varchar](500) NULL,
[PSale_Price] [varchar](500) NULL,
[PSale_Price_Code] [varchar](500) NULL,
[PSale_Recording_Date] [varchar](500) NULL,
[PSale_reo_flag] [varchar](500) NULL,
[PSale_distressed_sale_flag] [varchar](500) NULL,
[Prior_Transfer_date] [varchar](500) NULL,
[PValid_Book_Number] [varchar](500) NULL,
[PValid_Page_Number] [varchar](500) NULL,
[PValid_Document_Number] [varchar](500) NULL,
[PValid_Document_Type_Code] [varchar](500) NULL,
[PValid_Price] [varchar](500) NULL,
[PValid_Price_Code] [varchar](500) NULL,
[PValid_Recording_Date] [varchar](500) NULL,
[PValid_reo_flag] [varchar](500) NULL,
[PValid_distressed_sale_flag] [varchar](500) NULL,
[Prior_Sale_Date] [varchar](500) NULL,
[Recorders_Document_Number_from_Assessment] [varchar](500) NULL,
[Recorders_Book_Number_from_Assessment] [varchar](500) NULL,
[Recorders_Page_Number_from_Assessment] [varchar](500) NULL,
[Recording_Date_from_Assessment] [varchar](500) NULL,
[Document_Type_from_Assessment] [varchar](500) NULL,
[Sales_Price_from_Assessment] [varchar](500) NULL,
[Sales_Price_Code_from_Assessment] [varchar](500) NULL,
[Property_Full_Street_Address] [varchar](500) NULL,
[Property_City_Name] [varchar](500) NULL,
[Property_State] [varchar](500) NULL,
[Property_Zip_Code] [varchar](500) NULL,
[Property_Zip_Plus4Code] [varchar](500) NULL,
[Property_House_Number] [varchar](500) NULL,
[Property_Street_Direction_Left] [varchar](500) NULL,
[Property_Street_Name] [varchar](500) NULL,
[Property_Street_Suffix] [varchar](500) NULL,
[Property_Street_Direction_Right] [varchar](500) NULL,
[Property_Unit_Number] [varchar](500) NULL,
[Property_Unit_Type] [varchar](500) NULL,
[PA_Carrier_Route] [varchar](500) NULL,
[PA_Census_Tract] [varchar](500) NULL,
[PA_Latitude] [varchar](500) NULL,
[PA_Longitude] [varchar](500) NULL,
[Match_Code] [varchar](500) NULL,
[Location_Code] [varchar](500) NULL,
[Legal_Assessors_Map_Ref] [varchar](500) NULL,
[Legal_Brief_Description] [varchar](500) NULL,
[Legal_Brief_Description_FULL] [varchar](500) NULL,
[Legal_Section_Township__Range_Meridian] [varchar](500) NULL,
[Legal_Block] [varchar](500) NULL,
[Legal_Lot_Number] [varchar](500) NULL,
[Legal_City_Township_Municipality] [varchar](500) NULL,
[Legal_District] [varchar](500) NULL,
[Legal_Section] [varchar](500) NULL,
[Legal_Land_Lot] [varchar](500) NULL,
[Legal_Lot_Code] [varchar](500) NULL,
[Legal_Phase_Number] [varchar](500) NULL,
[Legal_Subdivision_Name] [varchar](500) NULL,
[Legal_Tract_Number] [varchar](500) NULL,
[Legal_Unit] [varchar](500) NULL,
[Assessed_Improvement_Value] [varchar](500) NULL,
[Assessed_Land_Value] [varchar](500) NULL,
[Total_Assessed_Value] [varchar](500) NULL,
[Assessment_Year] [varchar](500) NULL,
[California_HomeOwners_Exemption] [varchar](500) NULL,
[Tax_Exemption_Codes] [varchar](500) NULL,
[Market_Value_Improvement] [varchar](500) NULL,
[Market_Value_Land] [varchar](500) NULL,
[Total_Market_Value] [varchar](500) NULL,
[Market_Value_Year] [varchar](500) NULL,
[School_Tax_District_1] [varchar](500) NULL,
[School_Tax_District_1_Indicator] [varchar](500) NULL,
[School_Tax_District_2] [varchar](500) NULL,
[School_Tax_District_2_Indicator] [varchar](500) NULL,
[School_Tax_District_3] [varchar](500) NULL,
[School_Tax_District_3_Indicator] [varchar](500) NULL,
[Tax_Amount] [varchar](500) NULL,
[Tax_Year] [varchar](500) NULL,
[Tax_Delinquent_Year] [varchar](500) NULL,
[Tax_Rate_Code_Area] [varchar](500) NULL,
[Neighborhood_Code] [varchar](500) NULL,
[Condo_Project_Bldg_Name] [varchar](500) NULL,
[Old_APN] [varchar](500) NULL,
[Alt_Old_APN_Indicator] [varchar](500) NULL,
[Certification_Date] [varchar](500) NULL,
[Edition] [varchar](500) NULL,
[LotSize_Acres] [varchar](500) NULL,
[LotSize_Depth_Feet] [varchar](500) NULL,
[LotSize_Frontage_Feet] [varchar](500) NULL,
[LotSize_Square_Feet] [varchar](500) NULL,
[Lot_Size_or_Area] [varchar](500) NULL,
[Lot_Size_Area_Unit] [varchar](500) NULL,
[Original_Lot_Size_or_Area] [varchar](500) NULL,
[Topography] [varchar](500) NULL,
[Site_Influence] [varchar](500) NULL,
[Air_Conditioning] [varchar](500) NULL,
[Air_Conditioning_Type] [varchar](500) NULL,
[Amenities] [varchar](500) NULL,
[Amenities_2] [varchar](500) NULL,
[Basement] [varchar](500) NULL,
[Building_Area] [varchar](500) NULL,
[Building_Area_1] [varchar](500) NULL,
[Building_Area_1_Indicator] [varchar](500) NULL,
[Building_Area_2] [varchar](500) NULL,
[Building_Area_2_Indicator] [varchar](500) NULL,
[Building_Area_3] [varchar](500) NULL,
[Building_Area_3_Indicator] [varchar](500) NULL,
[Building_Area_4] [varchar](500) NULL,
[Building_Area_4_Indicator] [varchar](500) NULL,
[Building_Area_5] [varchar](500) NULL,
[Building_Area_5_Indicator] [varchar](500) NULL,
[Building_Area_6] [varchar](500) NULL,
[Building_Area_6_Indicator] [varchar](500) NULL,
[Building_Area_7] [varchar](500) NULL,
[Building_Area_7_Indicator] [varchar](500) NULL,
[Building_Class] [varchar](500) NULL,
[Building_Condition] [varchar](500) NULL,
[Building_Quality] [varchar](500) NULL,
[Comments_Summary_of_Building_Cards] [varchar](500) NULL,
[Effective_Year_Built] [varchar](500) NULL,
[Elevator] [varchar](500) NULL,
[Exterior_Walls] [varchar](500) NULL,
[Extra_Features_1_Area] [varchar](500) NULL,
[Extra_Features_1_Indicator] [varchar](500) NULL,
[Extra_Features_2_Area] [varchar](500) NULL,
[Extra_Features_2_Indicator] [varchar](500) NULL,
[Extra_Features_3_Area] [varchar](500) NULL,
[Extra_Features_3_Indicator] [varchar](500) NULL,
[Extra_Features_4_Area] [varchar](500) NULL,
[Extra_Features_4_Indicator] [varchar](500) NULL,
[Fireplace] [varchar](500) NULL,
[FLOOR_COVER] [varchar](500) NULL,
[Foundation] [varchar](500) NULL,
[Garage_Cars] [varchar](500) NULL,
[Garage_Type] [varchar](500) NULL,
[Heating] [varchar](500) NULL,
[Heating_Fuel_Type] [varchar](500) NULL,
[Interior_Walls] [varchar](500) NULL,
[Main_Building_Area_Indicator] [varchar](500) NULL,
[No_of_Buildings] [varchar](500) NULL,
[No_of_Stories] [varchar](500) NULL,
[Number_of_Baths] [varchar](500) NULL,
[Number_of_Bedrooms] [varchar](500) NULL,
[Number_of_Partial_Baths] [varchar](500) NULL,
[Number_of_Units] [varchar](500) NULL,
[Other_Impr_Building_Area_1] [varchar](500) NULL,
[Other_Impr_Building_Area_2] [varchar](500) NULL,
[Other_Impr_Building_Area_3] [varchar](500) NULL,
[Other_Impr_Building_Area_4] [varchar](500) NULL,
[Other_Impr_Building_Area_5] [varchar](500) NULL,
[Other_Impr_Building_Indicator_1] [varchar](500) NULL,
[Other_Impr_Building_Indicator_2] [varchar](500) NULL,
[Other_Impr_Building_Indicator_3] [varchar](500) NULL,
[Other_Impr_Building_Indicator_4] [varchar](500) NULL,
[Other_Impr_Building_Indicator_5] [varchar](500) NULL,
[Other_Rooms] [varchar](500) NULL,
[N_of_Plumbing_Fixtures] [varchar](500) NULL,
[Pool] [varchar](500) NULL,
[Roof_Cover] [varchar](500) NULL,
[Roof_Type] [varchar](500) NULL,
[Sewer] [varchar](500) NULL,
[Standardized_Land_Use_Code] [varchar](500) NULL,
[Style] [varchar](500) NULL,
[Total_Number_of_Rooms] [varchar](500) NULL,
[Type_Construction] [varchar](500) NULL,
[Water] [varchar](500) NULL,
[Year_Built] [varchar](500) NULL,
[Zoning] [varchar](500) NULL,
[Mtg01_lender_name_beneficiary] [varchar](500) NULL,
[Mtg01_lender_type] [varchar](500) NULL,
[Mtg01_original_date_of_contract] [varchar](500) NULL,
[Mtg01_recording_date] [varchar](500) NULL,
[Mtg01_Loan_Amount] [varchar](500) NULL,
[Mtg01_loan_type] [varchar](500) NULL,
[Mtg01_type_financing] [varchar](500) NULL,
[Mtg01_interest_rate] [varchar](500) NULL,
[Mtg01_due_date] [varchar](500) NULL,
[Mtg01_Adjustable_Rate_Rider] [varchar](500) NULL,
[Mtg01_Adjustable_Rate_Index] [varchar](500) NULL,
[Mtg01_Change_Index] [varchar](500) NULL,
[Mtg01_Rate_Change_Frequency] [varchar](500) NULL,
[Mtg01_Interest_Rate_Not_Greater_Than] [varchar](500) NULL,
[Mtg01_Interest_Rate_Not_Less_Than] [varchar](500) NULL,
[Mtg01_Maximum_Interest_Rate] [varchar](500) NULL,
[Mtg01_Interest_Only_Period] [varchar](500) NULL,
[Mtg01_fixed_step_conversion_rate_rider] [varchar](500) NULL,
[Mtg01_First_Change_Date] [varchar](500) NULL,
[Mtg01_First_Change_Period] [varchar](500) NULL,
[Mtg01_Prepayment_Rider] [varchar](500) NULL,
[Mtg01_Prepayment_Term_Penalty_Rider] [varchar](500) NULL,
[Mtg01_Title_Company_Name] [varchar](500) NULL,
[Mtg01_Lender_Name] [varchar](500) NULL,
[Mtg01_Lender_Mail_Full_Street_Address] [varchar](500) NULL,
[Mtg01_Lender_Mail_Unit] [varchar](500) NULL,
[Mtg01_Lender_Mail_City] [varchar](500) NULL,
[Mtg01_Lender_Mail_State] [varchar](500) NULL,
[Mtg01_Lender_Mail_Zip_Code] [varchar](500) NULL,
[Mtg01_Lender_Mail_Zip_Plus4Code] [varchar](500) NULL,
[Mtg01_Loan_Term_Months] [varchar](500) NULL,
[Mtg01_Loan_Term_Years] [varchar](500) NULL,
[Mtg01_loan_number] [varchar](500) NULL,
[Mtg01_Construction_Loan] [varchar](500) NULL,
[Mtg01_Cash_Purchase] [varchar](500) NULL,
[Mtg01_StandAlone_Refi] [varchar](500) NULL,
[Mtg01_Equity_Credit_Line] [varchar](500) NULL,
[Mtg01_Curr_Est_Bal] [varchar](500) NULL,
[Mtg01_Purpose_Of_Loan] [varchar](500) NULL,
[Mtg01_Purchase_Mtg_Ind] [varchar](500) NULL,
[Mtg01_Est_Monthly_P&I] [varchar](500) NULL,
[Mtg01_Est_Monthly_Principal] [varchar](500) NULL,
[Mtg01_Est_Monthly_Interest] [varchar](500) NULL,
[Mtg01_Curr_Est_Int_Rate] [varchar](500) NULL,
[Mtg01_Assigned_Lender_Name] [varchar](500) NULL,
[Mtg01_Assignment_Date] [varchar](500) NULL,
[Mtg01_Number_of_Assignments] [varchar](500) NULL,
[Mtg01_PreForeclosure_Status] [varchar](500) NULL,
[Mtg01_PreFcl_Recording_Date] [varchar](500) NULL,
[Mtg01_PreFcl_Filing_Date] [varchar](500) NULL,
[Mtg01_PreFcl_Case_Trustee_Sale_Nbr] [varchar](500) NULL,
[Mtg01_PreFcl_Auction_Date] [varchar](500) NULL,
[Mtg02_lender_name_beneficiary] [varchar](500) NULL,
[Mtg02_lender_type] [varchar](500) NULL,
[Mtg02_original_date_of_contract] [varchar](500) NULL,
[Mtg02_recording_date] [varchar](500) NULL,
[Mtg02_Loan_Amount] [varchar](500) NULL,
[Mtg02_loan_type] [varchar](500) NULL,
[Mtg02_type_financing] [varchar](500) NULL,
[Mtg02_interest_rate] [varchar](500) NULL,
[Mtg02_due_date] [varchar](500) NULL,
[Mtg02_Adjustable_Rate_Rider] [varchar](500) NULL,
[Mtg02_Adjustable_Rate_Index] [varchar](500) NULL,
[Mtg02_Change_Index] [varchar](500) NULL,
[Mtg02_Rate_Change_Frequency] [varchar](500) NULL,
[Mtg02_Interest_Rate_Not_Greater_Than] [varchar](500) NULL,
[Mtg02_Interest_Rate_Not_Less_Than] [varchar](500) NULL,
[Mtg02_Maximum_Interest_Rate] [varchar](500) NULL,
[Mtg02_Interest_Only_Period] [varchar](500) NULL,
[Mtg02_fixed_step_conversion_rate_rider] [varchar](500) NULL,
[Mtg02_First_Change_Date] [varchar](500) NULL,
[Mtg02_First_Change_Period] [varchar](500) NULL,
[Mtg02_Prepayment_Rider] [varchar](500) NULL,
[Mtg02_Prepayment_Term_Penalty_Rider] [varchar](500) NULL,
[Mtg02_Title_Company_Name] [varchar](500) NULL,
[Mtg02_Lender_Name] [varchar](500) NULL,
[Mtg02_Lender_Mail_Full_Street_Address] [varchar](500) NULL,
[Mtg02_Lender_Mail_Unit] [varchar](500) NULL,
[Mtg02_Lender_Mail_City] [varchar](500) NULL,
[Mtg02_Lender_Mail_State] [varchar](500) NULL,
[Mtg02_Lender_Mail_Zip_Code] [varchar](500) NULL,
[Mtg02_Lender_Mail_Zip_Plus4Code] [varchar](500) NULL,
[Mtg02_Loan_Term_Months] [varchar](500) NULL,
[Mtg02_Loan_Term_Years] [varchar](500) NULL,
[Mtg02_loan_number] [varchar](500) NULL,
[Mtg02_Construction_Loan] [varchar](500) NULL,
[Mtg02_Cash_Purchase] [varchar](500) NULL,
[Mtg02_StandAlone_Refi] [varchar](500) NULL,
[Mtg02_Equity_Credit_Line] [varchar](500) NULL,
[Mtg02_Curr_Est_Bal] [varchar](500) NULL,
[Mtg02_Purpose_Of_Loan] [varchar](500) NULL,
[Mtg02_Purchase_Mtg_Ind] [varchar](500) NULL,
[Mtg02_Est_Monthly_P&I] [varchar](500) NULL,
[Mtg02_Est_Monthly_Principal] [varchar](500) NULL,
[Mtg02_Est_Monthly_Interest] [varchar](500) NULL,
[Mtg02_Curr_Est_Int_Rate] [varchar](500) NULL,
[Mtg02_Assigned_Lender_Name] [varchar](500) NULL,
[Mtg02_Assignment_Date] [varchar](500) NULL,
[Mtg02_Number_of_Assignments] [varchar](500) NULL,
[Mtg02_PreForeclosure_Status] [varchar](500) NULL,
[Mtg02_PreFcl_Recording_Date] [varchar](500) NULL,
[Mtg02_PreFcl_Filing_Date] [varchar](500) NULL,
[Mtg02_PreFcl_Case_Trustee_Sale_Nbr] [varchar](500) NULL,
[Mtg02_PreFcl_Auction_Date] [varchar](500) NULL,
[Mtg03_lender_name_beneficiary] [varchar](500) NULL,
[Mtg03_lender_type] [varchar](500) NULL,
[Mtg03_original_date_of_contract] [varchar](500) NULL,
[Mtg03_recording_date] [varchar](500) NULL,
[Mtg03_Loan_Amount] [varchar](500) NULL,
[Mtg03_loan_type] [varchar](500) NULL,
[Mtg03_type_financing] [varchar](500) NULL,
[Mtg03_interest_rate] [varchar](500) NULL,
[Mtg03_due_date] [varchar](500) NULL,
[Mtg03_Adjustable_Rate_Rider] [varchar](500) NULL,
[Mtg03_Adjustable_Rate_Index] [varchar](500) NULL,
[Mtg03_Change_Index] [varchar](500) NULL,
[Mtg03_Rate_Change_Frequency] [varchar](500) NULL,
[Mtg03_Interest_Rate_Not_Greater_Than] [varchar](500) NULL,
[Mtg03_Interest_Rate_Not_Less_Than] [varchar](500) NULL,
[Mtg03_Maximum_Interest_Rate] [varchar](500) NULL,
[Mtg03_Interest_Only_Period] [varchar](500) NULL,
[Mtg03_fixed_step_conversion_rate_rider] [varchar](500) NULL,
[Mtg03_First_Change_Date] [varchar](500) NULL,
[Mtg03_First_Change_Period] [varchar](500) NULL,
[Mtg03_Prepayment_Rider] [varchar](500) NULL,
[Mtg03_Prepayment_Term_Penalty_Rider] [varchar](500) NULL,
[Mtg03_Title_Company_Name] [varchar](500) NULL,
[Mtg03_Lender_Name] [varchar](500) NULL,
[Mtg03_Lender_Mail_Full_Street_Address] [varchar](500) NULL,
[Mtg03_Lender_Mail_Unit] [varchar](500) NULL,
[Mtg03_Lender_Mail_City] [varchar](500) NULL,
[Mtg03_Lender_Mail_State] [varchar](500) NULL,
[Mtg03_Lender_Mail_Zip_Code] [varchar](500) NULL,
[Mtg03_Lender_Mail_Zip_Plus4Code] [varchar](500) NULL,
[Mtg03_Loan_Term_Months] [varchar](500) NULL,
[Mtg03_Loan_Term_Years] [varchar](500) NULL,
[Mtg03_loan_number] [varchar](500) NULL,
[Mtg03_Construction_Loan] [varchar](500) NULL,
[Mtg03_Cash_Purchase] [varchar](500) NULL,
[Mtg03_StandAlone_Refi] [varchar](500) NULL,
[Mtg03_Equity_Credit_Line] [varchar](500) NULL,
[Mtg03_Curr_Est_Bal] [varchar](500) NULL,
[Mtg03_Purpose_Of_Loan] [varchar](500) NULL,
[Mtg03_Purchase_Mtg_Ind] [varchar](500) NULL,
[Mtg03_Est_Monthly_P&I] [varchar](500) NULL,
[Mtg03_Est_Monthly_Principal] [varchar](500) NULL,
[Mtg03_Est_Monthly_Interest] [varchar](500) NULL,
[Mtg03_Curr_Est_Int_Rate] [varchar](500) NULL,
[Mtg03_Assigned_Lender_Name] [varchar](500) NULL,
[Mtg03_Assignment_Date] [varchar](500) NULL,
[Mtg03_Number_of_Assignments] [varchar](500) NULL,
[Mtg03_PreForeclosure_Status] [varchar](500) NULL,
[Mtg03_PreFcl_Recording_Date] [varchar](500) NULL,
[Mtg03_PreFcl_Filing_Date] [varchar](500) NULL,
[Mtg03_PreFcl_Case_Trustee_Sale_Nbr] [varchar](500) NULL,
[Mtg03_PreFcl_Auction_Date] [varchar](500) NULL,
[Mtg04_lender_name_beneficiary] [varchar](500) NULL,
[Mtg04_lender_type] [varchar](500) NULL,
[Mtg04_original_date_of_contract] [varchar](500) NULL,
[Mtg04_recording_date] [varchar](500) NULL,
[Mtg04_Loan_Amount] [varchar](500) NULL,
[Mtg04_loan_type] [varchar](500) NULL,
[Mtg04_type_financing] [varchar](500) NULL,
[Mtg04_interest_rate] [varchar](500) NULL,
[Mtg04_due_date] [varchar](500) NULL,
[Mtg04_Adjustable_Rate_Rider] [varchar](500) NULL,
[Mtg04_Adjustable_Rate_Index] [varchar](500) NULL,
[Mtg04_Change_Index] [varchar](500) NULL,
[Mtg04_Rate_Change_Frequency] [varchar](500) NULL,
[Mtg04_Interest_Rate_Not_Greater_Than] [varchar](500) NULL,
[Mtg04_Interest_Rate_Not_Less_Than] [varchar](500) NULL,
[Mtg04_Maximum_Interest_Rate] [varchar](500) NULL,
[Mtg04_Interest_Only_Period] [varchar](500) NULL,
[Mtg04_fixed_step_conversion_rate_rider] [varchar](500) NULL,
[Mtg04_First_Change_Date] [varchar](500) NULL,
[Mtg04_First_Change_Period] [varchar](500) NULL,
[Mtg04_Prepayment_Rider] [varchar](500) NULL,
[Mtg04_Prepayment_Term_Penalty_Rider] [varchar](500) NULL,
[Mtg04_Title_Company_Name] [varchar](500) NULL,
[Mtg04_Lender_Name] [varchar](500) NULL,
[Mtg04_Lender_Mail_Full_Street_Address] [varchar](500) NULL,
[Mtg04_Lender_Mail_Unit] [varchar](500) NULL,
[Mtg04_Lender_Mail_City] [varchar](500) NULL,
[Mtg04_Lender_Mail_State] [varchar](500) NULL,
[Mtg04_Lender_Mail_Zip_Code] [varchar](500) NULL,
[Mtg04_Lender_Mail_Zip_Plus4Code] [varchar](500) NULL,
[Mtg04_Loan_Term_Months] [varchar](500) NULL,
[Mtg04_Loan_Term_Years] [varchar](500) NULL,
[Mtg04_loan_number] [varchar](500) NULL,
[Mtg04_Construction_Loan] [varchar](500) NULL,
[Mtg04_Cash_Purchase] [varchar](500) NULL,
[Mtg04_StandAlone_Refi] [varchar](500) NULL,
[Mtg04_Equity_Credit_Line] [varchar](500) NULL,
[Mtg04_Curr_Est_Bal] [varchar](500) NULL,
[Mtg04_Purpose_Of_Loan] [varchar](500) NULL,
[Mtg04_Purchase_Mtg_Ind] [varchar](500) NULL,
[Mtg04_Est_Monthly_P&I] [varchar](500) NULL,
[Mtg04_Est_Monthly_Principal] [varchar](500) NULL,
[Mtg04_Est_Monthly_Interest] [varchar](500) NULL,
[Mtg04_Curr_Est_Int_Rate] [varchar](500) NULL,
[Mtg04_Assigned_Lender_Name] [varchar](500) NULL,
[Mtg04_Assignment_Date] [varchar](500) NULL,
[Mtg04_Number_of_Assignments] [varchar](500) NULL,
[Mtg04_PreForeclosure_Status] [varchar](500) NULL,
[Mtg04_PreFcl_Recording_Date] [varchar](500) NULL,
[Mtg04_PreFcl_Filing_Date] [varchar](500) NULL,
[Mtg04_PreFcl_Case_Trustee_Sale_Nbr] [varchar](500) NULL,
[Mtg04_PreFcl_Auction_Date] [varchar](500) NULL,
[Additional_Open_Lien_Count] [varchar](500) NULL,
[Additional_Open_Lien_Balance] [varchar](500) NULL,
[Total_Open_Lien_Count] [varchar](500) NULL,
[Total_Open_Lien_Balance] [varchar](500) NULL,
[Total_Financing_History_Count] [varchar](500) NULL,
[Current_Est_LTV_Combined] [varchar](500) NULL,
[Current_Est_LTV_Range_Code] [varchar](500) NULL,
[Current_Est_Equity_Dollars] [varchar](500) NULL,
[Current_Est_Equity_Range_Code] [varchar](500) NULL,
[Purchase_LTV] [varchar](500) NULL,
[Current_Foreclosure_Status] [varchar](500) NULL,
[Foreclosure_Recording_Date] [varchar](500) NULL,
[Foreclosure_filing_date] [varchar](500) NULL,
[Foreclosure_Case_Number] [varchar](500) NULL,
[Foreclosure_Auction_Date] [varchar](500) NULL,
[ESTIMATED_VALUE] [varchar](500) NULL,
[PRICE_RANGE_MIN] [varchar](500) NULL,
[PRICE_RANGE_MAX] [varchar](500) NULL,
[FSD_SCORE] [varchar](500) NULL,
[CONFIDENCE_SCORE] [varchar](500) NULL,
[QVM_Value_Range_Code] [varchar](500) NULL,
[QVM_asof_Date] [varchar](500) NULL,
[Trans_asof_Date] [varchar](500) NULL,
[Record_Creation_Date] [varchar](500) NULL,
[Quantarium_Version] [varchar](500) NULL

) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




/*Creating the main OpenLien Dataset table from the data dictionary*/




SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [Quantarium_OpenLienData](
	[Quantarium_Internal_PID] [INT]NOT NULL,
[FIPS_Code] [CHAR](5)NOT NULL,
[Assessors_Parcel_Number] [VARCHAR](45) NULL,
[Duplicate_APN] [VARCHAR](2) NULL,
[Tax_Account_Number] [VARCHAR](30) NULL,
[Current_Owner_Name] [VARCHAR](166) NULL,
[CO_Mail_Care_of_Name] [VARCHAR](60) NULL,
[CO_Mail_Street_Address] [VARCHAR](80) NULL,
[CO_Mailing_City] [VARCHAR](30) NULL,
[CO_Mailing_State] [VARCHAR](2) NULL,
[CO_Mailing_Zip_Code] [VARCHAR](5) NULL,
[CO_Mailing_Zip_Plus4Code] [VARCHAR](4) NULL,
[CO_Unit_Number] [VARCHAR](11) NULL,
[CO_Unit_Type] [VARCHAR](4) NULL,
[Mail_Care_Of_Name_Indicator] [VARCHAR](1) NULL,
[Owner_Occupied] [VARCHAR](1) NULL,
[Owner1FirstName] [VARCHAR](166) NULL,
[Owner1MiddleName] [VARCHAR](166) NULL,
[Owner1LastName] [VARCHAR](166) NULL,
[Owner2Firstname] [VARCHAR](166) NULL,
[Owner2MiddleName] [VARCHAR](166) NULL,
[Owner2LastName] [VARCHAR](166) NULL,
[ParsedOwnerSourceCode] [VARCHAR](1) NULL,
[Buyer_ID_Code_1] [VARCHAR](2) NULL,
[Buyer_Vesting_Code] [VARCHAR](2) NULL,
[Length_of_Residence_Months] [INT] NULL,
[Length_of_Residence_Code] [VARCHAR](2) NULL,
[Ownership_Start_Date] [VARCHAR](8) NULL,
[LSale_Book_Number] [VARCHAR](10) NULL,
[LSale_Page_Number] [VARCHAR](10) NULL,
[LSale_Document_Number] [VARCHAR](20) NULL,
[LSale_Document_Type_Code] [VARCHAR](2) NULL,
[LSale_Price] [VARCHAR](10) NULL,
[LSale_Price_Code] [VARCHAR](1) NULL,
[LSale_Recording_Date] [VARCHAR](8) NULL,
[LSale_reo_flag] [VARCHAR](1) NULL,
[LSale_distressed_sale_flag] [VARCHAR](1) NULL,
[Last_Transfer_Date] [VARCHAR](8) NULL,
[LValid_Book_Number] [VARCHAR](10) NULL,
[LValid_Page_Number] [VARCHAR](10) NULL,
[LValid_Document_Number] [VARCHAR](20) NULL,
[LValid_Document_Type_Code] [VARCHAR](2) NULL,
[LValid_Price] [VARCHAR](10) NULL,
[LValid_Price_Code] [VARCHAR](1) NULL,
[LValid_Recording_Date] [VARCHAR](8) NULL,
[LValid_reo_flag] [VARCHAR](1) NULL,
[LValid_distressed_sale_flag] [VARCHAR](1) NULL,
[Last_Sale_date] [VARCHAR](8) NULL,
[PSale_Book_Number] [VARCHAR](10) NULL,
[PSale_Page_Number] [VARCHAR](10) NULL,
[PSale_Document_Number] [VARCHAR](20) NULL,
[PSale_Document_Type_Code] [VARCHAR](2) NULL,
[PSale_Price] [VARCHAR](10) NULL,
[PSale_Price_Code] [VARCHAR](1) NULL,
[PSale_Recording_Date] [VARCHAR](8) NULL,
[PSale_reo_flag] [VARCHAR](1) NULL,
[PSale_distressed_sale_flag] [VARCHAR](1) NULL,
[Prior_Transfer_date] [VARCHAR](8) NULL,
[PValid_Book_Number] [VARCHAR](10) NULL,
[PValid_Page_Number] [VARCHAR](10) NULL,
[PValid_Document_Number] [VARCHAR](20) NULL,
[PValid_Document_Type_Code] [VARCHAR](2) NULL,
[PValid_Price] [VARCHAR](10) NULL,
[PValid_Price_Code] [VARCHAR](1) NULL,
[PValid_Recording_Date] [VARCHAR](8) NULL,
[PValid_reo_flag] [VARCHAR](1) NULL,
[PValid_distressed_sale_flag] [VARCHAR](1) NULL,
[Prior_Sale_Date] [VARCHAR](8) NULL,
[Recorders_Document_Number_from_Assessment] [VARCHAR](20) NULL,
[Recorders_Book_Number_from_Assessment] [VARCHAR](10) NULL,
[Recorders_Page_Number_from_Assessment] [VARCHAR](10) NULL,
[Recording_Date_from_Assessment] [VARCHAR](8) NULL,
[Document_Type_from_Assessment] [VARCHAR](25) NULL,
[Sales_Price_from_Assessment] [INT] NULL,
[Sales_Price_Code_from_Assessment] [VARCHAR](1) NULL,
[Property_Full_Street_Address] [VARCHAR](60) NULL,
[Property_City_Name] [VARCHAR](30) NULL,
[Property_State] [VARCHAR](2) NULL,
[Property_Zip_Code] [VARCHAR](5) NULL,
[Property_Zip_Plus4Code] [VARCHAR](4) NULL,
[Property_House_Number] [VARCHAR](13) NULL,
[Property_Street_Direction_Left] [VARCHAR](2) NULL,
[Property_Street_Name] [VARCHAR](40) NULL,
[Property_Street_Suffix] [VARCHAR](4) NULL,
[Property_Street_Direction_Right] [VARCHAR](2) NULL,
[Property_Unit_Number] [VARCHAR](11) NULL,
[Property_Unit_Type] [VARCHAR](4) NULL,
[PA_Carrier_Route] [VARCHAR](4) NULL,
[PA_Census_Tract] [VARCHAR](16) NULL,
[PA_Latitude] [VARCHAR](20) NULL,
[PA_Longitude] [VARCHAR](20) NULL,
[Match_Code] [VARCHAR](4) NULL,
[Location_Code] [VARCHAR](4) NULL,
[Legal_Assessors_Map_Ref] [VARCHAR](15) NULL,
[Legal_Brief_Description] [VARCHAR](200) NULL,
[Legal_Brief_Description_FULL] [VARCHAR](400) NULL,
[Legal_Section_Township__Range_Meridian] [VARCHAR](30) NULL,
[Legal_Block] [VARCHAR](7) NULL,
[Legal_Lot_Number] [VARCHAR](7) NULL,
[Legal_City_Township_Municipality] [VARCHAR](30) NULL,
[Legal_District] [VARCHAR](12) NULL,
[Legal_Section] [VARCHAR](7) NULL,
[Legal_Land_Lot] [VARCHAR](10) NULL,
[Legal_Lot_Code] [VARCHAR](2) NULL,
[Legal_Phase_Number] [VARCHAR](7) NULL,
[Legal_Subdivision_Name] [VARCHAR](40) NULL,
[Legal_Tract_Number] [VARCHAR](10) NULL,
[Legal_Unit] [VARCHAR](6) NULL,
[Assessed_Improvement_Value] [INT] NULL,
[Assessed_Land_Value] [INT] NULL,
[Total_Assessed_Value] [INT] NULL,
[Assessment_Year] [VARCHAR](4) NULL,
[California_HomeOwners_Exemption] [VARCHAR](1) NULL,
[Tax_Exemption_Codes] [VARCHAR](4) NULL,
[Market_Value_Improvement] [INT] NULL,
[Market_Value_Land] [INT] NULL,
[Total_Market_Value] [INT] NULL,
[Market_Value_Year] [VARCHAR](4) NULL,
[School_Tax_District_1] [VARCHAR](15) NULL,
[School_Tax_District_1_Indicator] [VARCHAR](1) NULL,
[School_Tax_District_2] [VARCHAR](15) NULL,
[School_Tax_District_2_Indicator] [VARCHAR](1) NULL,
[School_Tax_District_3] [VARCHAR](15) NULL,
[School_Tax_District_3_Indicator] [VARCHAR](1) NULL,
[Tax_Amount] [DECIMAL](11, 2) NULL,
[Tax_Year] [VARCHAR](4) NULL,
[Tax_Delinquent_Year] [VARCHAR](4) NULL,
[Tax_Rate_Code_Area] [VARCHAR](18) NULL,
[Neighborhood_Code] [VARCHAR](9) NULL,
[Condo_Project_Bldg_Name] [VARCHAR](20) NULL,
[Old_APN] [VARCHAR](31) NULL,
[Alt_Old_APN_Indicator] [VARCHAR](1) NULL,
[Certification_Date] [VARCHAR](8) NULL,
[Edition] [VARCHAR](2) NULL,
[LotSize_Acres] [VARCHAR](14) NULL,
[LotSize_Depth_Feet] [VARCHAR](10) NULL,
[LotSize_Frontage_Feet] [VARCHAR](10) NULL,
[LotSize_Square_Feet] [INT] NULL,
[Lot_Size_or_Area] [REAL] NULL,
[Lot_Size_Area_Unit] [VARCHAR](2) NULL,
[Original_Lot_Size_or_Area] [VARCHAR](14) NULL,
[Topography] [VARCHAR](1) NULL,
[Site_Influence] [VARCHAR](2) NULL,
[Air_Conditioning] [VARCHAR](1) NULL,
[Air_Conditioning_Type] [VARCHAR](1) NULL,
[Amenities] [VARCHAR](5) NULL,
[Amenities_2] [VARCHAR](5) NULL,
[Basement] [VARCHAR](1) NULL,
[Building_Area] [INT] NULL,
[Building_Area_1] [INT] NULL,
[Building_Area_1_Indicator] [VARCHAR](2) NULL,
[Building_Area_2] [INT] NULL,
[Building_Area_2_Indicator] [VARCHAR](2) NULL,
[Building_Area_3] [INT] NULL,
[Building_Area_3_Indicator] [VARCHAR](2) NULL,
[Building_Area_4] [INT] NULL,
[Building_Area_4_Indicator] [VARCHAR](2) NULL,
[Building_Area_5] [INT] NULL,
[Building_Area_5_Indicator] [VARCHAR](2) NULL,
[Building_Area_6] [INT] NULL,
[Building_Area_6_Indicator] [VARCHAR](2) NULL,
[Building_Area_7] [INT] NULL,
[Building_Area_7_Indicator] [VARCHAR](2) NULL,
[Building_Class] [VARCHAR](1) NULL,
[Building_Condition] [VARCHAR](1) NULL,
[Building_Quality] [VARCHAR](2) NULL,
[Comments_Summary_of_Building_Cards] [VARCHAR](120) NULL,
[Effective_Year_Built] [VARCHAR](4) NULL,
[Elevator] [VARCHAR](1) NULL,
[Exterior_Walls] [VARCHAR](1) NULL,
[Extra_Features_1_Area] [VARCHAR](9) NULL,
[Extra_Features_1_Indicator] [VARCHAR](2) NULL,
[Extra_Features_2_Area] [VARCHAR](9) NULL,
[Extra_Features_2_Indicator] [VARCHAR](2) NULL,
[Extra_Features_3_Area] [VARCHAR](9) NULL,
[Extra_Features_3_Indicator] [VARCHAR](2) NULL,
[Extra_Features_4_Area] [VARCHAR](9) NULL,
[Extra_Features_4_Indicator] [VARCHAR](2) NULL,
[Fireplace] [VARCHAR](1) NULL,
[FLOOR_COVER] [VARCHAR](2) NULL,
[Foundation] [VARCHAR](1) NULL,
[Garage_Cars] [INT] NULL,
[Garage_Type] [VARCHAR](1) NULL,
[Heating] [VARCHAR](1) NULL,
[Heating_Fuel_Type] [VARCHAR](1) NULL,
[Interior_Walls] [VARCHAR](1) NULL,
[Main_Building_Area_Indicator] [VARCHAR](1) NULL,
[No_of_Buildings] [INT] NULL,
[No_of_Stories] [VARCHAR](10) NULL,
[Number_of_Baths] [DECIMAL](5, 2) NULL,
[Number_of_Bedrooms] [INT] NULL,
[Number_of_Partial_Baths] [INT] NULL,
[Number_of_Units] [INT] NULL,
[Other_Impr_Building_Area_1] [VARCHAR](9) NULL,
[Other_Impr_Building_Area_2] [VARCHAR](9) NULL,
[Other_Impr_Building_Area_3] [VARCHAR](9) NULL,
[Other_Impr_Building_Area_4] [VARCHAR](9) NULL,
[Other_Impr_Building_Area_5] [VARCHAR](9) NULL,
[Other_Impr_Building_Indicator_1] [VARCHAR](2) NULL,
[Other_Impr_Building_Indicator_2] [VARCHAR](2) NULL,
[Other_Impr_Building_Indicator_3] [VARCHAR](2) NULL,
[Other_Impr_Building_Indicator_4] [VARCHAR](2) NULL,
[Other_Impr_Building_Indicator_5] [VARCHAR](2) NULL,
[Other_Rooms] [VARCHAR](5) NULL,
[N_of_Plumbing_Fixtures] [VARCHAR](3) NULL,
[Pool] [VARCHAR](1) NULL,
[Roof_Cover] [VARCHAR](1) NULL,
[Roof_Type] [VARCHAR](1) NULL,
[Sewer] [VARCHAR](1) NULL,
[Standardized_Land_Use_Code] [VARCHAR](4) NULL,
[Style] [VARCHAR](1) NULL,
[Total_Number_of_Rooms] [VARCHAR](2) NULL,
[Type_Construction] [VARCHAR](1) NULL,
[Water] [VARCHAR](1) NULL,
[Year_Built] [VARCHAR](4) NULL,
[Zoning] [VARCHAR](25) NULL,
[Mtg01_lender_name_beneficiary] [VARCHAR](40) NULL,
[Mtg01_lender_type] [VARCHAR](1) NULL,
[Mtg01_original_date_of_contract] [VARCHAR](8) NULL,
[Mtg01_recording_date] [VARCHAR](8) NULL,
[Mtg01_Loan_Amount] [INT] NULL,
[Mtg01_loan_type] [VARCHAR](1) NULL,
[Mtg01_type_financing] [VARCHAR](4) NULL,
[Mtg01_interest_rate] [DECIMAL](7, 5) NULL,
[Mtg01_due_date] [VARCHAR](8) NULL,
[Mtg01_Adjustable_Rate_Rider] [VARCHAR](1) NULL,
[Mtg01_Adjustable_Rate_Index] [VARCHAR](15) NULL,
[Mtg01_Change_Index] [DECIMAL](7, 5) NULL,
[Mtg01_Rate_Change_Frequency] [VARCHAR](1) NULL,
[Mtg01_Interest_Rate_Not_Greater_Than] [DECIMAL](7, 5) NULL,
[Mtg01_Interest_Rate_Not_Less_Than] [DECIMAL](7, 5) NULL,
[Mtg01_Maximum_Interest_Rate] [DECIMAL](7, 5) NULL,
[Mtg01_Interest_Only_Period] [VARCHAR](2) NULL,
[Mtg01_fixed_step_conversion_rate_rider] [VARCHAR](1) NULL,
[Mtg01_First_Change_Date] [VARCHAR](8) NULL,
[Mtg01_First_Change_Period] [INT] NULL,
[Mtg01_Prepayment_Rider] [VARCHAR](1) NULL,
[Mtg01_Prepayment_Term_Penalty_Rider] [VARCHAR](2) NULL,
[Mtg01_Title_Company_Name] [VARCHAR](28) NULL,
[Mtg01_Lender_Name] [VARCHAR](40) NULL,
[Mtg01_Lender_Mail_Full_Street_Address] [VARCHAR](60) NULL,
[Mtg01_Lender_Mail_Unit] [VARCHAR](11) NULL,
[Mtg01_Lender_Mail_City] [VARCHAR](30) NULL,
[Mtg01_Lender_Mail_State] [VARCHAR](2) NULL,
[Mtg01_Lender_Mail_Zip_Code] [VARCHAR](5) NULL,
[Mtg01_Lender_Mail_Zip_Plus4Code] [VARCHAR](4) NULL,
[Mtg01_Loan_Term_Months] [INT] NULL,
[Mtg01_Loan_Term_Years] [INT] NULL,
[Mtg01_loan_number] [VARCHAR](20) NULL,
[Mtg01_Construction_Loan] [VARCHAR](1) NULL,
[Mtg01_Cash_Purchase] [VARCHAR](1) NULL,
[Mtg01_StandAlone_Refi] [VARCHAR](1) NULL,
[Mtg01_Equity_Credit_Line] [VARCHAR](1) NULL,
[Mtg01_Curr_Est_Bal] [BIGINT] NULL,
[Mtg01_Purpose_Of_Loan] [VARCHAR](2) NULL,
[Mtg01_Purchase_Mtg_Ind] [VARCHAR](1) NULL,
[Mtg01_Est_Monthly_P&I] [DECIMAL](12, 2) NULL,
[Mtg01_Est_Monthly_Principal] [DECIMAL](12, 2) NULL,
[Mtg01_Est_Monthly_Interest] [DECIMAL](12, 2) NULL,
[Mtg01_Curr_Est_Int_Rate] [DECIMAL](7, 5) NULL,
[Mtg01_Assigned_Lender_Name] [VARCHAR](250) NULL,
[Mtg01_Assignment_Date] [VARCHAR](8) NULL,
[Mtg01_Number_of_Assignments] [INT] NULL,
[Mtg01_PreForeclosure_Status] [INT] NULL,
[Mtg01_PreFcl_Recording_Date] [VARCHAR](8) NULL,
[Mtg01_PreFcl_Filing_Date] [VARCHAR](8) NULL,
[Mtg01_PreFcl_Case_Trustee_Sale_Nbr] [VARCHAR](40) NULL,
[Mtg01_PreFcl_Auction_Date] [VARCHAR](8) NULL,
[Mtg02_lender_name_beneficiary] [VARCHAR](40) NULL,
[Mtg02_lender_type] [VARCHAR](1) NULL,
[Mtg02_original_date_of_contract] [VARCHAR](8) NULL,
[Mtg02_recording_date] [VARCHAR](8) NULL,
[Mtg02_Loan_Amount] [INT] NULL,
[Mtg02_loan_type] [VARCHAR](1) NULL,
[Mtg02_type_financing] [VARCHAR](4) NULL,
[Mtg02_interest_rate] [DECIMAL](7, 5) NULL,
[Mtg02_due_date] [VARCHAR](8) NULL,
[Mtg02_Adjustable_Rate_Rider] [VARCHAR](1) NULL,
[Mtg02_Adjustable_Rate_Index] [VARCHAR](15) NULL,
[Mtg02_Change_Index] [DECIMAL](7, 5) NULL,
[Mtg02_Rate_Change_Frequency] [VARCHAR](1) NULL,
[Mtg02_Interest_Rate_Not_Greater_Than] [DECIMAL](7, 5) NULL,
[Mtg02_Interest_Rate_Not_Less_Than] [DECIMAL](7, 5) NULL,
[Mtg02_Maximum_Interest_Rate] [DECIMAL](7, 5) NULL,
[Mtg02_Interest_Only_Period] [VARCHAR](2) NULL,
[Mtg02_fixed_step_conversion_rate_rider] [VARCHAR](1) NULL,
[Mtg02_First_Change_Date] [VARCHAR](8) NULL,
[Mtg02_First_Change_Period] [INT] NULL,
[Mtg02_Prepayment_Rider] [VARCHAR](1) NULL,
[Mtg02_Prepayment_Term_Penalty_Rider] [VARCHAR](2) NULL,
[Mtg02_Title_Company_Name] [VARCHAR](28) NULL,
[Mtg02_Lender_Name] [VARCHAR](40) NULL,
[Mtg02_Lender_Mail_Full_Street_Address] [VARCHAR](60) NULL,
[Mtg02_Lender_Mail_Unit] [VARCHAR](11) NULL,
[Mtg02_Lender_Mail_City] [VARCHAR](30) NULL,
[Mtg02_Lender_Mail_State] [VARCHAR](2) NULL,
[Mtg02_Lender_Mail_Zip_Code] [VARCHAR](5) NULL,
[Mtg02_Lender_Mail_Zip_Plus4Code] [VARCHAR](4) NULL,
[Mtg02_Loan_Term_Months] [INT] NULL,
[Mtg02_Loan_Term_Years] [INT] NULL,
[Mtg02_loan_number] [VARCHAR](20) NULL,
[Mtg02_Construction_Loan] [VARCHAR](1) NULL,
[Mtg02_Cash_Purchase] [VARCHAR](1) NULL,
[Mtg02_StandAlone_Refi] [VARCHAR](1) NULL,
[Mtg02_Equity_Credit_Line] [VARCHAR](1) NULL,
[Mtg02_Curr_Est_Bal] [BIGINT] NULL,
[Mtg02_Purpose_Of_Loan] [VARCHAR](2) NULL,
[Mtg02_Purchase_Mtg_Ind] [VARCHAR](1) NULL,
[Mtg02_Est_Monthly_P&I] [DECIMAL](12, 2) NULL,
[Mtg02_Est_Monthly_Principal] [DECIMAL](12, 2) NULL,
[Mtg02_Est_Monthly_Interest] [DECIMAL](12, 2) NULL,
[Mtg02_Curr_Est_Int_Rate] [DECIMAL](7, 5) NULL,
[Mtg02_Assigned_Lender_Name] [VARCHAR](250) NULL,
[Mtg02_Assignment_Date] [VARCHAR](8) NULL,
[Mtg02_Number_of_Assignments] [INT] NULL,
[Mtg02_PreForeclosure_Status] [INT] NULL,
[Mtg02_PreFcl_Recording_Date] [VARCHAR](8) NULL,
[Mtg02_PreFcl_Filing_Date] [VARCHAR](8) NULL,
[Mtg02_PreFcl_Case_Trustee_Sale_Nbr] [VARCHAR](40) NULL,
[Mtg02_PreFcl_Auction_Date] [VARCHAR](8) NULL,
[Mtg03_lender_name_beneficiary] [VARCHAR](40) NULL,
[Mtg03_lender_type] [VARCHAR](1) NULL,
[Mtg03_original_date_of_contract] [VARCHAR](8) NULL,
[Mtg03_recording_date] [VARCHAR](8) NULL,
[Mtg03_Loan_Amount] [INT] NULL,
[Mtg03_loan_type] [VARCHAR](1) NULL,
[Mtg03_type_financing] [VARCHAR](4) NULL,
[Mtg03_interest_rate] [DECIMAL](7, 5) NULL,
[Mtg03_due_date] [VARCHAR](8) NULL,
[Mtg03_Adjustable_Rate_Rider] [VARCHAR](1) NULL,
[Mtg03_Adjustable_Rate_Index] [VARCHAR](15) NULL,
[Mtg03_Change_Index] [DECIMAL](7, 5) NULL,
[Mtg03_Rate_Change_Frequency] [VARCHAR](1) NULL,
[Mtg03_Interest_Rate_Not_Greater_Than] [DECIMAL](7, 5) NULL,
[Mtg03_Interest_Rate_Not_Less_Than] [DECIMAL](7, 5) NULL,
[Mtg03_Maximum_Interest_Rate] [DECIMAL](7, 5) NULL,
[Mtg03_Interest_Only_Period] [VARCHAR](2) NULL,
[Mtg03_fixed_step_conversion_rate_rider] [VARCHAR](1) NULL,
[Mtg03_First_Change_Date] [VARCHAR](8) NULL,
[Mtg03_First_Change_Period] [INT] NULL,
[Mtg03_Prepayment_Rider] [VARCHAR](1) NULL,
[Mtg03_Prepayment_Term_Penalty_Rider] [VARCHAR](2) NULL,
[Mtg03_Title_Company_Name] [VARCHAR](28) NULL,
[Mtg03_Lender_Name] [VARCHAR](40) NULL,
[Mtg03_Lender_Mail_Full_Street_Address] [VARCHAR](60) NULL,
[Mtg03_Lender_Mail_Unit] [VARCHAR](11) NULL,
[Mtg03_Lender_Mail_City] [VARCHAR](30) NULL,
[Mtg03_Lender_Mail_State] [VARCHAR](2) NULL,
[Mtg03_Lender_Mail_Zip_Code] [VARCHAR](5) NULL,
[Mtg03_Lender_Mail_Zip_Plus4Code] [VARCHAR](4) NULL,
[Mtg03_Loan_Term_Months] [INT] NULL,
[Mtg03_Loan_Term_Years] [INT] NULL,
[Mtg03_loan_number] [VARCHAR](20) NULL,
[Mtg03_Construction_Loan] [VARCHAR](1) NULL,
[Mtg03_Cash_Purchase] [VARCHAR](1) NULL,
[Mtg03_StandAlone_Refi] [VARCHAR](1) NULL,
[Mtg03_Equity_Credit_Line] [VARCHAR](1) NULL,
[Mtg03_Curr_Est_Bal] [BIGINT] NULL,
[Mtg03_Purpose_Of_Loan] [VARCHAR](2) NULL,
[Mtg03_Purchase_Mtg_Ind] [VARCHAR](1) NULL,
[Mtg03_Est_Monthly_P&I] [DECIMAL](12, 2) NULL,
[Mtg03_Est_Monthly_Principal] [DECIMAL](12, 2) NULL,
[Mtg03_Est_Monthly_Interest] [DECIMAL](12, 2) NULL,
[Mtg03_Curr_Est_Int_Rate] [DECIMAL](7, 5) NULL,
[Mtg03_Assigned_Lender_Name] [VARCHAR](250) NULL,
[Mtg03_Assignment_Date] [VARCHAR](8) NULL,
[Mtg03_Number_of_Assignments] [INT] NULL,
[Mtg03_PreForeclosure_Status] [INT] NULL,
[Mtg03_PreFcl_Recording_Date] [VARCHAR](8) NULL,
[Mtg03_PreFcl_Filing_Date] [VARCHAR](8) NULL,
[Mtg03_PreFcl_Case_Trustee_Sale_Nbr] [VARCHAR](40) NULL,
[Mtg03_PreFcl_Auction_Date] [VARCHAR](8) NULL,
[Mtg04_lender_name_beneficiary] [VARCHAR](40) NULL,
[Mtg04_lender_type] [VARCHAR](1) NULL,
[Mtg04_original_date_of_contract] [VARCHAR](8) NULL,
[Mtg04_recording_date] [VARCHAR](8) NULL,
[Mtg04_Loan_Amount] [INT] NULL,
[Mtg04_loan_type] [VARCHAR](1) NULL,
[Mtg04_type_financing] [VARCHAR](4) NULL,
[Mtg04_interest_rate] [DECIMAL](7, 5) NULL,
[Mtg04_due_date] [VARCHAR](8) NULL,
[Mtg04_Adjustable_Rate_Rider] [VARCHAR](1) NULL,
[Mtg04_Adjustable_Rate_Index] [VARCHAR](15) NULL,
[Mtg04_Change_Index] [DECIMAL](7, 5) NULL,
[Mtg04_Rate_Change_Frequency] [VARCHAR](1) NULL,
[Mtg04_Interest_Rate_Not_Greater_Than] [DECIMAL](7, 5) NULL,
[Mtg04_Interest_Rate_Not_Less_Than] [DECIMAL](7, 5) NULL,
[Mtg04_Maximum_Interest_Rate] [DECIMAL](7, 5) NULL,
[Mtg04_Interest_Only_Period] [VARCHAR](2) NULL,
[Mtg04_fixed_step_conversion_rate_rider] [VARCHAR](1) NULL,
[Mtg04_First_Change_Date] [VARCHAR](8) NULL,
[Mtg04_First_Change_Period] [INT] NULL,
[Mtg04_Prepayment_Rider] [VARCHAR](1) NULL,
[Mtg04_Prepayment_Term_Penalty_Rider] [VARCHAR](2) NULL,
[Mtg04_Title_Company_Name] [VARCHAR](28) NULL,
[Mtg04_Lender_Name] [VARCHAR](40) NULL,
[Mtg04_Lender_Mail_Full_Street_Address] [VARCHAR](60) NULL,
[Mtg04_Lender_Mail_Unit] [VARCHAR](11) NULL,
[Mtg04_Lender_Mail_City] [VARCHAR](30) NULL,
[Mtg04_Lender_Mail_State] [VARCHAR](2) NULL,
[Mtg04_Lender_Mail_Zip_Code] [VARCHAR](5) NULL,
[Mtg04_Lender_Mail_Zip_Plus4Code] [VARCHAR](4) NULL,
[Mtg04_Loan_Term_Months] [INT] NULL,
[Mtg04_Loan_Term_Years] [INT] NULL,
[Mtg04_loan_number] [VARCHAR](20) NULL,
[Mtg04_Construction_Loan] [VARCHAR](1) NULL,
[Mtg04_Cash_Purchase] [VARCHAR](1) NULL,
[Mtg04_StandAlone_Refi] [VARCHAR](1) NULL,
[Mtg04_Equity_Credit_Line] [VARCHAR](1) NULL,
[Mtg04_Curr_Est_Bal] [BIGINT] NULL,
[Mtg04_Purpose_Of_Loan] [VARCHAR](2) NULL,
[Mtg04_Purchase_Mtg_Ind] [VARCHAR](1) NULL,
[Mtg04_Est_Monthly_P&I] [DECIMAL](12, 2) NULL,
[Mtg04_Est_Monthly_Principal] [DECIMAL](12, 2) NULL,
[Mtg04_Est_Monthly_Interest] [DECIMAL](12, 2) NULL,
[Mtg04_Curr_Est_Int_Rate] [DECIMAL](7, 5) NULL,
[Mtg04_Assigned_Lender_Name] [VARCHAR](250) NULL,
[Mtg04_Assignment_Date] [VARCHAR](8) NULL,
[Mtg04_Number_of_Assignments] [INT] NULL,
[Mtg04_PreForeclosure_Status] [INT] NULL,
[Mtg04_PreFcl_Recording_Date] [VARCHAR](8) NULL,
[Mtg04_PreFcl_Filing_Date] [VARCHAR](8) NULL,
[Mtg04_PreFcl_Case_Trustee_Sale_Nbr] [VARCHAR](40) NULL,
[Mtg04_PreFcl_Auction_Date] [VARCHAR](8) NULL,
[Additional_Open_Lien_Count] [INT] NULL,
[Additional_Open_Lien_Balance] [BIGINT] NULL,
[Total_Open_Lien_Count] [INT] NULL,
[Total_Open_Lien_Balance] [BIGINT] NULL,
[Total_Financing_History_Count] [INT] NULL,
[Current_Est_LTV_Combined] [DECIMAL](7, 4) NULL,
[Current_Est_LTV_Range_Code] [VARCHAR](2) NULL,
[Current_Est_Equity_Dollars] [BIGINT] NULL,
[Current_Est_Equity_Range_Code] [VARCHAR](2) NULL,
[Purchase_LTV] [DECIMAL](7, 4) NULL,
[Current_Foreclosure_Status] [INT] NULL,
[Foreclosure_Recording_Date] [VARCHAR](8) NULL,
[Foreclosure_filing_date] [VARCHAR](8) NULL,
[Foreclosure_Case_Number] [VARCHAR](40) NULL,
[Foreclosure_Auction_Date] [VARCHAR](8) NULL,
[ESTIMATED_VALUE] [INT] NULL,
[PRICE_RANGE_MIN] [INT] NULL,
[PRICE_RANGE_MAX] [INT] NULL,
[FSD_SCORE] [INT] NULL,
[CONFIDENCE_SCORE] [INT] NULL,
[QVM_Value_Range_Code] [VARCHAR](2) NULL,
[QVM_asof_Date] [VARCHAR](8) NULL,
[Trans_asof_Date] [VARCHAR](8) NULL,
[Record_Creation_Date] [VARCHAR](8) NULL,
[Quantarium_Version] [VARCHAR](8) NULL

PRIMARY KEY CLUSTERED 
(
	[Quantarium_Internal_PID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO



/*This script inserts the data from the Staging table to the main OpenLien table */


INSERT INTO Quantarium_OpenLienData

      ([Quantarium_Internal_PID],
[FIPS_Code],
[Assessors_Parcel_Number],
[Duplicate_APN],
[Tax_Account_Number],
[Current_Owner_Name],
[CO_Mail_Care_of_Name],
[CO_Mail_Street_Address],
[CO_Mailing_City],
[CO_Mailing_State],
[CO_Mailing_Zip_Code],
[CO_Mailing_Zip_Plus4Code],
[CO_Unit_Number],
[CO_Unit_Type],
[Mail_Care_Of_Name_Indicator],
[Owner_Occupied],
[Owner1FirstName],
[Owner1MiddleName],
[Owner1LastName],
[Owner2Firstname],
[Owner2MiddleName],
[Owner2LastName],
[ParsedOwnerSourceCode],
[Buyer_ID_Code_1],
[Buyer_Vesting_Code],
[Length_of_Residence_Months],
[Length_of_Residence_Code],
[Ownership_Start_Date],
[LSale_Book_Number],
[LSale_Page_Number],
[LSale_Document_Number],
[LSale_Document_Type_Code],
[LSale_Price],
[LSale_Price_Code],
[LSale_Recording_Date],
[LSale_reo_flag],
[LSale_distressed_sale_flag],
[Last_Transfer_Date],
[LValid_Book_Number],
[LValid_Page_Number],
[LValid_Document_Number],
[LValid_Document_Type_Code],
[LValid_Price],
[LValid_Price_Code],
[LValid_Recording_Date],
[LValid_reo_flag],
[LValid_distressed_sale_flag],
[Last_Sale_date],
[PSale_Book_Number],
[PSale_Page_Number],
[PSale_Document_Number],
[PSale_Document_Type_Code],
[PSale_Price],
[PSale_Price_Code],
[PSale_Recording_Date],
[PSale_reo_flag],
[PSale_distressed_sale_flag],
[Prior_Transfer_date],
[PValid_Book_Number],
[PValid_Page_Number],
[PValid_Document_Number],
[PValid_Document_Type_Code],
[PValid_Price],
[PValid_Price_Code],
[PValid_Recording_Date],
[PValid_reo_flag],
[PValid_distressed_sale_flag],
[Prior_Sale_Date],
[Recorders_Document_Number_from_Assessment],
[Recorders_Book_Number_from_Assessment],
[Recorders_Page_Number_from_Assessment],
[Recording_Date_from_Assessment],
[Document_Type_from_Assessment],
[Sales_Price_from_Assessment],
[Sales_Price_Code_from_Assessment],
[Property_Full_Street_Address],
[Property_City_Name],
[Property_State],
[Property_Zip_Code],
[Property_Zip_Plus4Code],
[Property_House_Number],
[Property_Street_Direction_Left],
[Property_Street_Name],
[Property_Street_Suffix],
[Property_Street_Direction_Right],
[Property_Unit_Number],
[Property_Unit_Type],
[PA_Carrier_Route],
[PA_Census_Tract],
[PA_Latitude],
[PA_Longitude],
[Match_Code],
[Location_Code],
[Legal_Assessors_Map_Ref],
[Legal_Brief_Description],
[Legal_Brief_Description_FULL],
[Legal_Section_Township__Range_Meridian],
[Legal_Block],
[Legal_Lot_Number],
[Legal_City_Township_Municipality],
[Legal_District],
[Legal_Section],
[Legal_Land_Lot],
[Legal_Lot_Code],
[Legal_Phase_Number],
[Legal_Subdivision_Name],
[Legal_Tract_Number],
[Legal_Unit],
[Assessed_Improvement_Value],
[Assessed_Land_Value],
[Total_Assessed_Value],
[Assessment_Year],
[California_HomeOwners_Exemption],
[Tax_Exemption_Codes],
[Market_Value_Improvement],
[Market_Value_Land],
[Total_Market_Value],
[Market_Value_Year],
[School_Tax_District_1],
[School_Tax_District_1_Indicator],
[School_Tax_District_2],
[School_Tax_District_2_Indicator],
[School_Tax_District_3],
[School_Tax_District_3_Indicator],
[Tax_Amount],
[Tax_Year],
[Tax_Delinquent_Year],
[Tax_Rate_Code_Area],
[Neighborhood_Code],
[Condo_Project_Bldg_Name],
[Old_APN],
[Alt_Old_APN_Indicator],
[Certification_Date],
[Edition],
[LotSize_Acres],
[LotSize_Depth_Feet],
[LotSize_Frontage_Feet],
[LotSize_Square_Feet],
[Lot_Size_or_Area],
[Lot_Size_Area_Unit],
[Original_Lot_Size_or_Area],
[Topography],
[Site_Influence],
[Air_Conditioning],
[Air_Conditioning_Type],
[Amenities],
[Amenities_2],
[Basement],
[Building_Area],
[Building_Area_1],
[Building_Area_1_Indicator],
[Building_Area_2],
[Building_Area_2_Indicator],
[Building_Area_3],
[Building_Area_3_Indicator],
[Building_Area_4],
[Building_Area_4_Indicator],
[Building_Area_5],
[Building_Area_5_Indicator],
[Building_Area_6],
[Building_Area_6_Indicator],
[Building_Area_7],
[Building_Area_7_Indicator],
[Building_Class],
[Building_Condition],
[Building_Quality],
[Comments_Summary_of_Building_Cards],
[Effective_Year_Built],
[Elevator],
[Exterior_Walls],
[Extra_Features_1_Area],
[Extra_Features_1_Indicator],
[Extra_Features_2_Area],
[Extra_Features_2_Indicator],
[Extra_Features_3_Area],
[Extra_Features_3_Indicator],
[Extra_Features_4_Area],
[Extra_Features_4_Indicator],
[Fireplace],
[FLOOR_COVER],
[Foundation],
[Garage_Cars],
[Garage_Type],
[Heating],
[Heating_Fuel_Type],
[Interior_Walls],
[Main_Building_Area_Indicator],
[No_of_Buildings],
[No_of_Stories],
[Number_of_Baths],
[Number_of_Bedrooms],
[Number_of_Partial_Baths],
[Number_of_Units],
[Other_Impr_Building_Area_1],
[Other_Impr_Building_Area_2],
[Other_Impr_Building_Area_3],
[Other_Impr_Building_Area_4],
[Other_Impr_Building_Area_5],
[Other_Impr_Building_Indicator_1],
[Other_Impr_Building_Indicator_2],
[Other_Impr_Building_Indicator_3],
[Other_Impr_Building_Indicator_4],
[Other_Impr_Building_Indicator_5],
[Other_Rooms],
[N_of_Plumbing_Fixtures],
[Pool],
[Roof_Cover],
[Roof_Type],
[Sewer],
[Standardized_Land_Use_Code],
[Style],
[Total_Number_of_Rooms],
[Type_Construction],
[Water],
[Year_Built],
[Zoning],
[Mtg01_lender_name_beneficiary],
[Mtg01_lender_type],
[Mtg01_original_date_of_contract],
[Mtg01_recording_date],
[Mtg01_Loan_Amount],
[Mtg01_loan_type],
[Mtg01_type_financing],
[Mtg01_interest_rate],
[Mtg01_due_date],
[Mtg01_Adjustable_Rate_Rider],
[Mtg01_Adjustable_Rate_Index],
[Mtg01_Change_Index],
[Mtg01_Rate_Change_Frequency],
[Mtg01_Interest_Rate_Not_Greater_Than],
[Mtg01_Interest_Rate_Not_Less_Than],
[Mtg01_Maximum_Interest_Rate],
[Mtg01_Interest_Only_Period],
[Mtg01_fixed_step_conversion_rate_rider],
[Mtg01_First_Change_Date],
[Mtg01_First_Change_Period],
[Mtg01_Prepayment_Rider],
[Mtg01_Prepayment_Term_Penalty_Rider],
[Mtg01_Title_Company_Name],
[Mtg01_Lender_Name],
[Mtg01_Lender_Mail_Full_Street_Address],
[Mtg01_Lender_Mail_Unit],
[Mtg01_Lender_Mail_City],
[Mtg01_Lender_Mail_State],
[Mtg01_Lender_Mail_Zip_Code],
[Mtg01_Lender_Mail_Zip_Plus4Code],
[Mtg01_Loan_Term_Months],
[Mtg01_Loan_Term_Years],
[Mtg01_loan_number],
[Mtg01_Construction_Loan],
[Mtg01_Cash_Purchase],
[Mtg01_StandAlone_Refi],
[Mtg01_Equity_Credit_Line],
[Mtg01_Curr_Est_Bal],
[Mtg01_Purpose_Of_Loan],
[Mtg01_Purchase_Mtg_Ind],
[Mtg01_Est_Monthly_P&I],
[Mtg01_Est_Monthly_Principal],
[Mtg01_Est_Monthly_Interest],
[Mtg01_Curr_Est_Int_Rate],
[Mtg01_Assigned_Lender_Name],
[Mtg01_Assignment_Date],
[Mtg01_Number_of_Assignments],
[Mtg01_PreForeclosure_Status],
[Mtg01_PreFcl_Recording_Date],
[Mtg01_PreFcl_Filing_Date],
[Mtg01_PreFcl_Case_Trustee_Sale_Nbr],
[Mtg01_PreFcl_Auction_Date],
[Mtg02_lender_name_beneficiary],
[Mtg02_lender_type],
[Mtg02_original_date_of_contract],
[Mtg02_recording_date],
[Mtg02_Loan_Amount],
[Mtg02_loan_type],
[Mtg02_type_financing],
[Mtg02_interest_rate],
[Mtg02_due_date],
[Mtg02_Adjustable_Rate_Rider],
[Mtg02_Adjustable_Rate_Index],
[Mtg02_Change_Index],
[Mtg02_Rate_Change_Frequency],
[Mtg02_Interest_Rate_Not_Greater_Than],
[Mtg02_Interest_Rate_Not_Less_Than],
[Mtg02_Maximum_Interest_Rate],
[Mtg02_Interest_Only_Period],
[Mtg02_fixed_step_conversion_rate_rider],
[Mtg02_First_Change_Date],
[Mtg02_First_Change_Period],
[Mtg02_Prepayment_Rider],
[Mtg02_Prepayment_Term_Penalty_Rider],
[Mtg02_Title_Company_Name],
[Mtg02_Lender_Name],
[Mtg02_Lender_Mail_Full_Street_Address],
[Mtg02_Lender_Mail_Unit],
[Mtg02_Lender_Mail_City],
[Mtg02_Lender_Mail_State],
[Mtg02_Lender_Mail_Zip_Code],
[Mtg02_Lender_Mail_Zip_Plus4Code],
[Mtg02_Loan_Term_Months],
[Mtg02_Loan_Term_Years],
[Mtg02_loan_number],
[Mtg02_Construction_Loan],
[Mtg02_Cash_Purchase],
[Mtg02_StandAlone_Refi],
[Mtg02_Equity_Credit_Line],
[Mtg02_Curr_Est_Bal],
[Mtg02_Purpose_Of_Loan],
[Mtg02_Purchase_Mtg_Ind],
[Mtg02_Est_Monthly_P&I],
[Mtg02_Est_Monthly_Principal],
[Mtg02_Est_Monthly_Interest],
[Mtg02_Curr_Est_Int_Rate],
[Mtg02_Assigned_Lender_Name],
[Mtg02_Assignment_Date],
[Mtg02_Number_of_Assignments],
[Mtg02_PreForeclosure_Status],
[Mtg02_PreFcl_Recording_Date],
[Mtg02_PreFcl_Filing_Date],
[Mtg02_PreFcl_Case_Trustee_Sale_Nbr],
[Mtg02_PreFcl_Auction_Date],
[Mtg03_lender_name_beneficiary],
[Mtg03_lender_type],
[Mtg03_original_date_of_contract],
[Mtg03_recording_date],
[Mtg03_Loan_Amount],
[Mtg03_loan_type],
[Mtg03_type_financing],
[Mtg03_interest_rate],
[Mtg03_due_date],
[Mtg03_Adjustable_Rate_Rider],
[Mtg03_Adjustable_Rate_Index],
[Mtg03_Change_Index],
[Mtg03_Rate_Change_Frequency],
[Mtg03_Interest_Rate_Not_Greater_Than],
[Mtg03_Interest_Rate_Not_Less_Than],
[Mtg03_Maximum_Interest_Rate],
[Mtg03_Interest_Only_Period],
[Mtg03_fixed_step_conversion_rate_rider],
[Mtg03_First_Change_Date],
[Mtg03_First_Change_Period],
[Mtg03_Prepayment_Rider],
[Mtg03_Prepayment_Term_Penalty_Rider],
[Mtg03_Title_Company_Name],
[Mtg03_Lender_Name],
[Mtg03_Lender_Mail_Full_Street_Address],
[Mtg03_Lender_Mail_Unit],
[Mtg03_Lender_Mail_City],
[Mtg03_Lender_Mail_State],
[Mtg03_Lender_Mail_Zip_Code],
[Mtg03_Lender_Mail_Zip_Plus4Code],
[Mtg03_Loan_Term_Months],
[Mtg03_Loan_Term_Years],
[Mtg03_loan_number],
[Mtg03_Construction_Loan],
[Mtg03_Cash_Purchase],
[Mtg03_StandAlone_Refi],
[Mtg03_Equity_Credit_Line],
[Mtg03_Curr_Est_Bal],
[Mtg03_Purpose_Of_Loan],
[Mtg03_Purchase_Mtg_Ind],
[Mtg03_Est_Monthly_P&I],
[Mtg03_Est_Monthly_Principal],
[Mtg03_Est_Monthly_Interest],
[Mtg03_Curr_Est_Int_Rate],
[Mtg03_Assigned_Lender_Name],
[Mtg03_Assignment_Date],
[Mtg03_Number_of_Assignments],
[Mtg03_PreForeclosure_Status],
[Mtg03_PreFcl_Recording_Date],
[Mtg03_PreFcl_Filing_Date],
[Mtg03_PreFcl_Case_Trustee_Sale_Nbr],
[Mtg03_PreFcl_Auction_Date],
[Mtg04_lender_name_beneficiary],
[Mtg04_lender_type],
[Mtg04_original_date_of_contract],
[Mtg04_recording_date],
[Mtg04_Loan_Amount],
[Mtg04_loan_type],
[Mtg04_type_financing],
[Mtg04_interest_rate],
[Mtg04_due_date],
[Mtg04_Adjustable_Rate_Rider],
[Mtg04_Adjustable_Rate_Index],
[Mtg04_Change_Index],
[Mtg04_Rate_Change_Frequency],
[Mtg04_Interest_Rate_Not_Greater_Than],
[Mtg04_Interest_Rate_Not_Less_Than],
[Mtg04_Maximum_Interest_Rate],
[Mtg04_Interest_Only_Period],
[Mtg04_fixed_step_conversion_rate_rider],
[Mtg04_First_Change_Date],
[Mtg04_First_Change_Period],
[Mtg04_Prepayment_Rider],
[Mtg04_Prepayment_Term_Penalty_Rider],
[Mtg04_Title_Company_Name],
[Mtg04_Lender_Name],
[Mtg04_Lender_Mail_Full_Street_Address],
[Mtg04_Lender_Mail_Unit],
[Mtg04_Lender_Mail_City],
[Mtg04_Lender_Mail_State],
[Mtg04_Lender_Mail_Zip_Code],
[Mtg04_Lender_Mail_Zip_Plus4Code],
[Mtg04_Loan_Term_Months],
[Mtg04_Loan_Term_Years],
[Mtg04_loan_number],
[Mtg04_Construction_Loan],
[Mtg04_Cash_Purchase],
[Mtg04_StandAlone_Refi],
[Mtg04_Equity_Credit_Line],
[Mtg04_Curr_Est_Bal],
[Mtg04_Purpose_Of_Loan],
[Mtg04_Purchase_Mtg_Ind],
[Mtg04_Est_Monthly_P&I],
[Mtg04_Est_Monthly_Principal],
[Mtg04_Est_Monthly_Interest],
[Mtg04_Curr_Est_Int_Rate],
[Mtg04_Assigned_Lender_Name],
[Mtg04_Assignment_Date],
[Mtg04_Number_of_Assignments],
[Mtg04_PreForeclosure_Status],
[Mtg04_PreFcl_Recording_Date],
[Mtg04_PreFcl_Filing_Date],
[Mtg04_PreFcl_Case_Trustee_Sale_Nbr],
[Mtg04_PreFcl_Auction_Date],
[Additional_Open_Lien_Count],
[Additional_Open_Lien_Balance],
[Total_Open_Lien_Count],
[Total_Open_Lien_Balance],
[Total_Financing_History_Count],
[Current_Est_LTV_Combined],
[Current_Est_LTV_Range_Code],
[Current_Est_Equity_Dollars],
[Current_Est_Equity_Range_Code],
[Purchase_LTV],
[Current_Foreclosure_Status],
[Foreclosure_Recording_Date],
[Foreclosure_filing_date],
[Foreclosure_Case_Number],
[Foreclosure_Auction_Date],
[ESTIMATED_VALUE],
[PRICE_RANGE_MIN],
[PRICE_RANGE_MAX],
[FSD_SCORE],
[CONFIDENCE_SCORE],
[QVM_Value_Range_Code],
[QVM_asof_Date],
[Trans_asof_Date],
[Record_Creation_Date],
[Quantarium_Version]

)
SELECT
CONVERT([INT],RTRIM(LTRIM(Quantarium_Internal_PID))),
CONVERT([CHAR](5),RTRIM(LTRIM(FIPS_Code))),
CONVERT([VARCHAR](45),RTRIM(LTRIM(Assessors_Parcel_Number))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Duplicate_APN))),
CONVERT([VARCHAR](30),RTRIM(LTRIM(Tax_Account_Number))),
CONVERT([VARCHAR](166),RTRIM(LTRIM(Current_Owner_Name))),
CONVERT([VARCHAR](60),RTRIM(LTRIM(CO_Mail_Care_of_Name))),
CONVERT([VARCHAR](80),RTRIM(LTRIM(CO_Mail_Street_Address))),
CONVERT([VARCHAR](30),RTRIM(LTRIM(CO_Mailing_City))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(CO_Mailing_State))),
CONVERT([VARCHAR](5),RTRIM(LTRIM(CO_Mailing_Zip_Code))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(CO_Mailing_Zip_Plus4Code))),
CONVERT([VARCHAR](11),RTRIM(LTRIM(CO_Unit_Number))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(CO_Unit_Type))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mail_Care_Of_Name_Indicator))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Owner_Occupied))),
CONVERT([VARCHAR](166),RTRIM(LTRIM(Owner1FirstName))),
CONVERT([VARCHAR](166),RTRIM(LTRIM(Owner1MiddleName))),
CONVERT([VARCHAR](166),RTRIM(LTRIM(Owner1LastName))),
CONVERT([VARCHAR](166),RTRIM(LTRIM(Owner2Firstname))),
CONVERT([VARCHAR](166),RTRIM(LTRIM(Owner2MiddleName))),
CONVERT([VARCHAR](166),RTRIM(LTRIM(Owner2LastName))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(ParsedOwnerSourceCode))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Buyer_ID_Code_1))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Buyer_Vesting_Code))),
CONVERT([INT],RTRIM(LTRIM(Length_of_Residence_Months))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Length_of_Residence_Code))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Ownership_Start_Date))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(LSale_Book_Number))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(LSale_Page_Number))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(LSale_Document_Number))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(LSale_Document_Type_Code))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(LSale_Price))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(LSale_Price_Code))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(LSale_Recording_Date))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(LSale_reo_flag))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(LSale_distressed_sale_flag))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Last_Transfer_Date))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(LValid_Book_Number))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(LValid_Page_Number))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(LValid_Document_Number))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(LValid_Document_Type_Code))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(LValid_Price))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(LValid_Price_Code))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(LValid_Recording_Date))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(LValid_reo_flag))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(LValid_distressed_sale_flag))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Last_Sale_date))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(PSale_Book_Number))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(PSale_Page_Number))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(PSale_Document_Number))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(PSale_Document_Type_Code))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(PSale_Price))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(PSale_Price_Code))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(PSale_Recording_Date))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(PSale_reo_flag))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(PSale_distressed_sale_flag))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Prior_Transfer_date))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(PValid_Book_Number))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(PValid_Page_Number))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(PValid_Document_Number))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(PValid_Document_Type_Code))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(PValid_Price))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(PValid_Price_Code))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(PValid_Recording_Date))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(PValid_reo_flag))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(PValid_distressed_sale_flag))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Prior_Sale_Date))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(Recorders_Document_Number_from_Assessment))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(Recorders_Book_Number_from_Assessment))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(Recorders_Page_Number_from_Assessment))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Recording_Date_from_Assessment))),
CONVERT([VARCHAR](25),RTRIM(LTRIM(Document_Type_from_Assessment))),
CONVERT([INT],RTRIM(LTRIM(Sales_Price_from_Assessment))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Sales_Price_Code_from_Assessment))),
CONVERT([VARCHAR](60),RTRIM(LTRIM(Property_Full_Street_Address))),
CONVERT([VARCHAR](30),RTRIM(LTRIM(Property_City_Name))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Property_State))),
CONVERT([VARCHAR](5),RTRIM(LTRIM(Property_Zip_Code))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Property_Zip_Plus4Code))),
CONVERT([VARCHAR](13),RTRIM(LTRIM(Property_House_Number))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Property_Street_Direction_Left))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Property_Street_Name))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Property_Street_Suffix))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Property_Street_Direction_Right))),
CONVERT([VARCHAR](11),RTRIM(LTRIM(Property_Unit_Number))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Property_Unit_Type))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(PA_Carrier_Route))),
CONVERT([VARCHAR](16),RTRIM(LTRIM(PA_Census_Tract))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(PA_Latitude))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(PA_Longitude))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Match_Code))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Location_Code))),
CONVERT([VARCHAR](15),RTRIM(LTRIM(Legal_Assessors_Map_Ref))),
CONVERT([VARCHAR](200),RTRIM(LTRIM(Legal_Brief_Description))),
CONVERT([VARCHAR](400),RTRIM(LTRIM(Legal_Brief_Description_FULL))),
CONVERT([VARCHAR](30),RTRIM(LTRIM(Legal_Section_Township__Range_Meridian))),
CONVERT([VARCHAR](7),RTRIM(LTRIM(Legal_Block))),
CONVERT([VARCHAR](7),RTRIM(LTRIM(Legal_Lot_Number))),
CONVERT([VARCHAR](30),RTRIM(LTRIM(Legal_City_Township_Municipality))),
CONVERT([VARCHAR](12),RTRIM(LTRIM(Legal_District))),
CONVERT([VARCHAR](7),RTRIM(LTRIM(Legal_Section))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(Legal_Land_Lot))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Legal_Lot_Code))),
CONVERT([VARCHAR](7),RTRIM(LTRIM(Legal_Phase_Number))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Legal_Subdivision_Name))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(Legal_Tract_Number))),
CONVERT([VARCHAR](6),RTRIM(LTRIM(Legal_Unit))),
CONVERT([INT],RTRIM(LTRIM(Assessed_Improvement_Value))),
CONVERT([INT],RTRIM(LTRIM(Assessed_Land_Value))),
CONVERT([INT],RTRIM(LTRIM(Total_Assessed_Value))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Assessment_Year))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(California_HomeOwners_Exemption))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Tax_Exemption_Codes))),
CONVERT([INT],RTRIM(LTRIM(Market_Value_Improvement))),
CONVERT([INT],RTRIM(LTRIM(Market_Value_Land))),
CONVERT([INT],RTRIM(LTRIM(Total_Market_Value))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Market_Value_Year))),
CONVERT([VARCHAR](15),RTRIM(LTRIM(School_Tax_District_1))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(School_Tax_District_1_Indicator))),
CONVERT([VARCHAR](15),RTRIM(LTRIM(School_Tax_District_2))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(School_Tax_District_2_Indicator))),
CONVERT([VARCHAR](15),RTRIM(LTRIM(School_Tax_District_3))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(School_Tax_District_3_Indicator))),
CONVERT([DECIMAL](11, 2),RTRIM(LTRIM(Tax_Amount))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Tax_Year))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Tax_Delinquent_Year))),
CONVERT([VARCHAR](18),RTRIM(LTRIM(Tax_Rate_Code_Area))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Neighborhood_Code))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(Condo_Project_Bldg_Name))),
CONVERT([VARCHAR](31),RTRIM(LTRIM(Old_APN))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Alt_Old_APN_Indicator))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Certification_Date))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Edition))),
CONVERT([VARCHAR](14),RTRIM(LTRIM(LotSize_Acres))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(LotSize_Depth_Feet))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(LotSize_Frontage_Feet))),
CONVERT([INT],RTRIM(LTRIM(LotSize_Square_Feet))),
CONVERT([REAL],RTRIM(LTRIM(Lot_Size_or_Area))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Lot_Size_Area_Unit))),
CONVERT([VARCHAR](14),RTRIM(LTRIM(Original_Lot_Size_or_Area))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Topography))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Site_Influence))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Air_Conditioning))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Air_Conditioning_Type))),
CONVERT([VARCHAR](5),RTRIM(LTRIM(Amenities))),
CONVERT([VARCHAR](5),RTRIM(LTRIM(Amenities_2))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Basement))),
CONVERT([INT],RTRIM(LTRIM(Building_Area))),
CONVERT([INT],RTRIM(LTRIM(Building_Area_1))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Building_Area_1_Indicator))),
CONVERT([INT],RTRIM(LTRIM(Building_Area_2))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Building_Area_2_Indicator))),
CONVERT([INT],RTRIM(LTRIM(Building_Area_3))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Building_Area_3_Indicator))),
CONVERT([INT],RTRIM(LTRIM(Building_Area_4))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Building_Area_4_Indicator))),
CONVERT([INT],RTRIM(LTRIM(Building_Area_5))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Building_Area_5_Indicator))),
CONVERT([INT],RTRIM(LTRIM(Building_Area_6))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Building_Area_6_Indicator))),
CONVERT([INT],RTRIM(LTRIM(Building_Area_7))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Building_Area_7_Indicator))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Building_Class))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Building_Condition))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Building_Quality))),
CONVERT([VARCHAR](120),RTRIM(LTRIM(Comments_Summary_of_Building_Cards))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Effective_Year_Built))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Elevator))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Exterior_Walls))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Extra_Features_1_Area))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Extra_Features_1_Indicator))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Extra_Features_2_Area))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Extra_Features_2_Indicator))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Extra_Features_3_Area))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Extra_Features_3_Indicator))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Extra_Features_4_Area))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Extra_Features_4_Indicator))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Fireplace))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(FLOOR_COVER))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Foundation))),
CONVERT([INT],RTRIM(LTRIM(Garage_Cars))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Garage_Type))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Heating))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Heating_Fuel_Type))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Interior_Walls))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Main_Building_Area_Indicator))),
CONVERT([INT],RTRIM(LTRIM(No_of_Buildings))),
CONVERT([VARCHAR](10),RTRIM(LTRIM(No_of_Stories))),
CONVERT([DECIMAL](5, 2),RTRIM(LTRIM(Number_of_Baths))),
CONVERT([INT],RTRIM(LTRIM(Number_of_Bedrooms))),
CONVERT([INT],RTRIM(LTRIM(Number_of_Partial_Baths))),
CONVERT([INT],RTRIM(LTRIM(Number_of_Units))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Other_Impr_Building_Area_1))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Other_Impr_Building_Area_2))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Other_Impr_Building_Area_3))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Other_Impr_Building_Area_4))),
CONVERT([VARCHAR](9),RTRIM(LTRIM(Other_Impr_Building_Area_5))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Other_Impr_Building_Indicator_1))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Other_Impr_Building_Indicator_2))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Other_Impr_Building_Indicator_3))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Other_Impr_Building_Indicator_4))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Other_Impr_Building_Indicator_5))),
CONVERT([VARCHAR](5),RTRIM(LTRIM(Other_Rooms))),
CONVERT([VARCHAR](3),RTRIM(LTRIM(N_of_Plumbing_Fixtures))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Pool))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Roof_Cover))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Roof_Type))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Sewer))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Standardized_Land_Use_Code))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Style))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Total_Number_of_Rooms))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Type_Construction))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Water))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Year_Built))),
CONVERT([VARCHAR](25),RTRIM(LTRIM(Zoning))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg01_lender_name_beneficiary))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_lender_type))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg01_original_date_of_contract))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg01_recording_date))),
CONVERT([INT],RTRIM(LTRIM(Mtg01_Loan_Amount))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_loan_type))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Mtg01_type_financing))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg01_interest_rate))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg01_due_date))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_Adjustable_Rate_Rider))),
CONVERT([VARCHAR](15),RTRIM(LTRIM(Mtg01_Adjustable_Rate_Index))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg01_Change_Index))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_Rate_Change_Frequency))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg01_Interest_Rate_Not_Greater_Than))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg01_Interest_Rate_Not_Less_Than))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg01_Maximum_Interest_Rate))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg01_Interest_Only_Period))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_fixed_step_conversion_rate_rider))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg01_First_Change_Date))),
CONVERT([INT],RTRIM(LTRIM(Mtg01_First_Change_Period))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_Prepayment_Rider))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg01_Prepayment_Term_Penalty_Rider))),
CONVERT([VARCHAR](28),RTRIM(LTRIM(Mtg01_Title_Company_Name))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg01_Lender_Name))),
CONVERT([VARCHAR](60),RTRIM(LTRIM(Mtg01_Lender_Mail_Full_Street_Address))),
CONVERT([VARCHAR](11),RTRIM(LTRIM(Mtg01_Lender_Mail_Unit))),
CONVERT([VARCHAR](30),RTRIM(LTRIM(Mtg01_Lender_Mail_City))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg01_Lender_Mail_State))),
CONVERT([VARCHAR](5),RTRIM(LTRIM(Mtg01_Lender_Mail_Zip_Code))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Mtg01_Lender_Mail_Zip_Plus4Code))),
CONVERT([INT],RTRIM(LTRIM(Mtg01_Loan_Term_Months))),
CONVERT([INT],RTRIM(LTRIM(Mtg01_Loan_Term_Years))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(Mtg01_loan_number))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_Construction_Loan))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_Cash_Purchase))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_StandAlone_Refi))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_Equity_Credit_Line))),
CONVERT([BIGINT],RTRIM(LTRIM(Mtg01_Curr_Est_Bal))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg01_Purpose_Of_Loan))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg01_Purchase_Mtg_Ind))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg01_Est_Monthly_P&I))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg01_Est_Monthly_Principal))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg01_Est_Monthly_Interest))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg01_Curr_Est_Int_Rate))),
CONVERT([VARCHAR](250),RTRIM(LTRIM(Mtg01_Assigned_Lender_Name))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg01_Assignment_Date))),
CONVERT([INT],RTRIM(LTRIM(Mtg01_Number_of_Assignments))),
CONVERT([INT],RTRIM(LTRIM(Mtg01_PreForeclosure_Status))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg01_PreFcl_Recording_Date))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg01_PreFcl_Filing_Date))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg01_PreFcl_Case_Trustee_Sale_Nbr))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg01_PreFcl_Auction_Date))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg02_lender_name_beneficiary))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_lender_type))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg02_original_date_of_contract))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg02_recording_date))),
CONVERT([INT],RTRIM(LTRIM(Mtg02_Loan_Amount))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_loan_type))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Mtg02_type_financing))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg02_interest_rate))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg02_due_date))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_Adjustable_Rate_Rider))),
CONVERT([VARCHAR](15),RTRIM(LTRIM(Mtg02_Adjustable_Rate_Index))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg02_Change_Index))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_Rate_Change_Frequency))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg02_Interest_Rate_Not_Greater_Than))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg02_Interest_Rate_Not_Less_Than))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg02_Maximum_Interest_Rate))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg02_Interest_Only_Period))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_fixed_step_conversion_rate_rider))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg02_First_Change_Date))),
CONVERT([INT],RTRIM(LTRIM(Mtg02_First_Change_Period))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_Prepayment_Rider))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg02_Prepayment_Term_Penalty_Rider))),
CONVERT([VARCHAR](28),RTRIM(LTRIM(Mtg02_Title_Company_Name))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg02_Lender_Name))),
CONVERT([VARCHAR](60),RTRIM(LTRIM(Mtg02_Lender_Mail_Full_Street_Address))),
CONVERT([VARCHAR](11),RTRIM(LTRIM(Mtg02_Lender_Mail_Unit))),
CONVERT([VARCHAR](30),RTRIM(LTRIM(Mtg02_Lender_Mail_City))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg02_Lender_Mail_State))),
CONVERT([VARCHAR](5),RTRIM(LTRIM(Mtg02_Lender_Mail_Zip_Code))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Mtg02_Lender_Mail_Zip_Plus4Code))),
CONVERT([INT],RTRIM(LTRIM(Mtg02_Loan_Term_Months))),
CONVERT([INT],RTRIM(LTRIM(Mtg02_Loan_Term_Years))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(Mtg02_loan_number))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_Construction_Loan))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_Cash_Purchase))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_StandAlone_Refi))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_Equity_Credit_Line))),
CONVERT([BIGINT],RTRIM(LTRIM(Mtg02_Curr_Est_Bal))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg02_Purpose_Of_Loan))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg02_Purchase_Mtg_Ind))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg02_Est_Monthly_P&I))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg02_Est_Monthly_Principal))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg02_Est_Monthly_Interest))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg02_Curr_Est_Int_Rate))),
CONVERT([VARCHAR](250),RTRIM(LTRIM(Mtg02_Assigned_Lender_Name))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg02_Assignment_Date))),
CONVERT([INT],RTRIM(LTRIM(Mtg02_Number_of_Assignments))),
CONVERT([INT],RTRIM(LTRIM(Mtg02_PreForeclosure_Status))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg02_PreFcl_Recording_Date))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg02_PreFcl_Filing_Date))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg02_PreFcl_Case_Trustee_Sale_Nbr))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg02_PreFcl_Auction_Date))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg03_lender_name_beneficiary))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_lender_type))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg03_original_date_of_contract))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg03_recording_date))),
CONVERT([INT],RTRIM(LTRIM(Mtg03_Loan_Amount))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_loan_type))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Mtg03_type_financing))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg03_interest_rate))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg03_due_date))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_Adjustable_Rate_Rider))),
CONVERT([VARCHAR](15),RTRIM(LTRIM(Mtg03_Adjustable_Rate_Index))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg03_Change_Index))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_Rate_Change_Frequency))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg03_Interest_Rate_Not_Greater_Than))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg03_Interest_Rate_Not_Less_Than))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg03_Maximum_Interest_Rate))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg03_Interest_Only_Period))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_fixed_step_conversion_rate_rider))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg03_First_Change_Date))),
CONVERT([INT],RTRIM(LTRIM(Mtg03_First_Change_Period))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_Prepayment_Rider))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg03_Prepayment_Term_Penalty_Rider))),
CONVERT([VARCHAR](28),RTRIM(LTRIM(Mtg03_Title_Company_Name))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg03_Lender_Name))),
CONVERT([VARCHAR](60),RTRIM(LTRIM(Mtg03_Lender_Mail_Full_Street_Address))),
CONVERT([VARCHAR](11),RTRIM(LTRIM(Mtg03_Lender_Mail_Unit))),
CONVERT([VARCHAR](30),RTRIM(LTRIM(Mtg03_Lender_Mail_City))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg03_Lender_Mail_State))),
CONVERT([VARCHAR](5),RTRIM(LTRIM(Mtg03_Lender_Mail_Zip_Code))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Mtg03_Lender_Mail_Zip_Plus4Code))),
CONVERT([INT],RTRIM(LTRIM(Mtg03_Loan_Term_Months))),
CONVERT([INT],RTRIM(LTRIM(Mtg03_Loan_Term_Years))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(Mtg03_loan_number))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_Construction_Loan))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_Cash_Purchase))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_StandAlone_Refi))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_Equity_Credit_Line))),
CONVERT([BIGINT],RTRIM(LTRIM(Mtg03_Curr_Est_Bal))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg03_Purpose_Of_Loan))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg03_Purchase_Mtg_Ind))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg03_Est_Monthly_P&I))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg03_Est_Monthly_Principal))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg03_Est_Monthly_Interest))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg03_Curr_Est_Int_Rate))),
CONVERT([VARCHAR](250),RTRIM(LTRIM(Mtg03_Assigned_Lender_Name))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg03_Assignment_Date))),
CONVERT([INT],RTRIM(LTRIM(Mtg03_Number_of_Assignments))),
CONVERT([INT],RTRIM(LTRIM(Mtg03_PreForeclosure_Status))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg03_PreFcl_Recording_Date))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg03_PreFcl_Filing_Date))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg03_PreFcl_Case_Trustee_Sale_Nbr))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg03_PreFcl_Auction_Date))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg04_lender_name_beneficiary))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_lender_type))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg04_original_date_of_contract))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg04_recording_date))),
CONVERT([INT],RTRIM(LTRIM(Mtg04_Loan_Amount))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_loan_type))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Mtg04_type_financing))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg04_interest_rate))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg04_due_date))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_Adjustable_Rate_Rider))),
CONVERT([VARCHAR](15),RTRIM(LTRIM(Mtg04_Adjustable_Rate_Index))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg04_Change_Index))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_Rate_Change_Frequency))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg04_Interest_Rate_Not_Greater_Than))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg04_Interest_Rate_Not_Less_Than))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg04_Maximum_Interest_Rate))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg04_Interest_Only_Period))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_fixed_step_conversion_rate_rider))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg04_First_Change_Date))),
CONVERT([INT],RTRIM(LTRIM(Mtg04_First_Change_Period))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_Prepayment_Rider))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg04_Prepayment_Term_Penalty_Rider))),
CONVERT([VARCHAR](28),RTRIM(LTRIM(Mtg04_Title_Company_Name))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg04_Lender_Name))),
CONVERT([VARCHAR](60),RTRIM(LTRIM(Mtg04_Lender_Mail_Full_Street_Address))),
CONVERT([VARCHAR](11),RTRIM(LTRIM(Mtg04_Lender_Mail_Unit))),
CONVERT([VARCHAR](30),RTRIM(LTRIM(Mtg04_Lender_Mail_City))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg04_Lender_Mail_State))),
CONVERT([VARCHAR](5),RTRIM(LTRIM(Mtg04_Lender_Mail_Zip_Code))),
CONVERT([VARCHAR](4),RTRIM(LTRIM(Mtg04_Lender_Mail_Zip_Plus4Code))),
CONVERT([INT],RTRIM(LTRIM(Mtg04_Loan_Term_Months))),
CONVERT([INT],RTRIM(LTRIM(Mtg04_Loan_Term_Years))),
CONVERT([VARCHAR](20),RTRIM(LTRIM(Mtg04_loan_number))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_Construction_Loan))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_Cash_Purchase))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_StandAlone_Refi))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_Equity_Credit_Line))),
CONVERT([BIGINT],RTRIM(LTRIM(Mtg04_Curr_Est_Bal))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Mtg04_Purpose_Of_Loan))),
CONVERT([VARCHAR](1),RTRIM(LTRIM(Mtg04_Purchase_Mtg_Ind))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg04_Est_Monthly_P&I))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg04_Est_Monthly_Principal))),
CONVERT([DECIMAL](12, 2),RTRIM(LTRIM(Mtg04_Est_Monthly_Interest))),
CONVERT([DECIMAL](7, 5),RTRIM(LTRIM(Mtg04_Curr_Est_Int_Rate))),
CONVERT([VARCHAR](250),RTRIM(LTRIM(Mtg04_Assigned_Lender_Name))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg04_Assignment_Date))),
CONVERT([INT],RTRIM(LTRIM(Mtg04_Number_of_Assignments))),
CONVERT([INT],RTRIM(LTRIM(Mtg04_PreForeclosure_Status))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg04_PreFcl_Recording_Date))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg04_PreFcl_Filing_Date))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Mtg04_PreFcl_Case_Trustee_Sale_Nbr))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Mtg04_PreFcl_Auction_Date))),
CONVERT([INT],RTRIM(LTRIM(Additional_Open_Lien_Count))),
CONVERT([BIGINT],RTRIM(LTRIM(Additional_Open_Lien_Balance))),
CONVERT([INT],RTRIM(LTRIM(Total_Open_Lien_Count))),
CONVERT([BIGINT],RTRIM(LTRIM(Total_Open_Lien_Balance))),
CONVERT([INT],RTRIM(LTRIM(Total_Financing_History_Count))),
CONVERT([DECIMAL](7, 4),RTRIM(LTRIM(Current_Est_LTV_Combined))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Current_Est_LTV_Range_Code))),
CONVERT([BIGINT],RTRIM(LTRIM(Current_Est_Equity_Dollars))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(Current_Est_Equity_Range_Code))),
CONVERT([DECIMAL](7, 4),RTRIM(LTRIM(Purchase_LTV))),
CONVERT([INT],RTRIM(LTRIM(Current_Foreclosure_Status))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Foreclosure_Recording_Date))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Foreclosure_filing_date))),
CONVERT([VARCHAR](40),RTRIM(LTRIM(Foreclosure_Case_Number))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Foreclosure_Auction_Date))),
CONVERT([INT],RTRIM(LTRIM(ESTIMATED_VALUE))),
CONVERT([INT],RTRIM(LTRIM(PRICE_RANGE_MIN))),
CONVERT([INT],RTRIM(LTRIM(PRICE_RANGE_MAX))),
CONVERT([INT],RTRIM(LTRIM(FSD_SCORE))),
CONVERT([INT],RTRIM(LTRIM(CONFIDENCE_SCORE))),
CONVERT([VARCHAR](2),RTRIM(LTRIM(QVM_Value_Range_Code))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(QVM_asof_Date))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Trans_asof_Date))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Record_Creation_Date))),
CONVERT([VARCHAR](8),RTRIM(LTRIM(Quantarium_Version)))

FROM Quantarium_Staging_OpenLienData (nolock)
OpenLien.sql
Displaying OpenLien.sql.